### ISSUE TITLE
How can i check for already opened entry?

### ISSUE THREAD

**Issue by maxsupermanhd** [kuba--/zip#104]

**Comment by kuba--** [comment]
@maxsupermanhd right now there is no _intuitive_ way e.g. _is_opened_ function, but as a trick/workaround you can use `const char *zip_entry_name(struct zip_t *zip);` function. 
If an entry was closed (or not opened) this function should return `NULL`

**Comment by kuba--** [comment]
@maxsupermanhd - does it work for you?

**Comment by kuba--** [comment]
@maxsupermanhd ?
