### ISSUE TITLE
Add support for zip64

### ISSUE THREAD

**Issue by kuba--** [kuba--/zip#109]
So far, the library does not support 64bit zip archives.
It's mainly related to following issues:
- https://github.com/kuba--/zip/issues/107
- https://github.com/kuba--/zip/issues/81

**Comment by maxsupermanhd** [comment]
Can you please make some kind of function witch will look up if zip is 64 bit or not. That will be very useful.

**Comment by maxsupermanhd** [comment]
Any news about this? (have nice project that heavily depends on zip reading)

**Comment by kuba--** [comment]
I hope, I'll have more time in next days

**Comment by kuba--** [comment]
But 

> Can you please make some kind of function witch will look up if zip is 64 bit or not. That will be very useful.

Btw. So far, I hope you noticed `extern int zip_is64(struct zip_t *zip);` which was added long time ago.

**Comment by brentp** [comment]
Is the number of files still limited to 65536? I see a few commits related to this, but it's not clear what limitations remain. Thanks!

**Comment by brentp** [comment]
I ran some tests and it is indeed still limited to 65536 files and a total compressed size of ~ 4.2GB

**Comment by kuba--** [comment]
Yeah, mostly it's still 32 bit library (mainly due to miniz). We can just recognize some x64 settings, and that's all.
Zip directory still uses on 32 bits values.

**Comment by brentp** [comment]
thanks for the reply. miniz does support zip64, or am I mistaken?

**Comment by kuba--** [comment]
> thanks for the reply. miniz does support zip64, or am I mistaken?

I have to take a look what has been changed in miniz, over time. But we already use the latest miniz version (2.2.0).

**Comment by kuba--** [comment]
Should be fixed by https://github.com/kuba--/zip/pull/215
