### ISSUE TITLE
Make password protected zip files

### ISSUE THREAD

**Issue by kuba--** [kuba--/zip#12]
TBD

**Comment by kuba--** [comment]
Spec.: https://www.loc.gov/preservation/digital/formats/digformatspecs/APPNOTE%2820120901%29_Version_6.3.3.txt

**Comment by mllamazares** [comment]
Was this functionality finally implemented? Is there any example of use? Thanks!

**Comment by kuba--** [comment]
@mllamazares unfortunately not - I don't have time to implement it and I should add support for zip64, first (it's higher priority).
But any help wanted:)
