### ISSUE TITLE
Miniz is out of date, and no way to avoid symbol clash

### ISSUE THREAD

**Issue by SoylentGraham** [kuba--/zip#120]
I have a project/lib that already includes miniz from somewhere else, (a PNG encoder/decoder) so I end up with multiple symbols.

As both were using this header-only lib at `1.15`, I've deleted both and replaced with https://github.com/richgel999/miniz (`2.1.0`) which is released as a `.c` and a `.h` so I don't have multiple symbols.

I can see the benefit of having a single include in your library, so I propose being able to make a `NO_MINIZ_INCLUDE` macro I can define before including `zip.h` so I can include my own `miniz.h` first (which has no definitions)

(Will submit a PR at some point, but making a note here first)

**Comment by SoylentGraham** [comment]
Actually, this was not a trivial change at all... (lots of the other c&h miniz build have structs/funcs/macros that this library uses defined in the .c)
Quick fix for now on my side is (in my other miniz include) is to `#include` it inside a c++ namespace and remove all the `extern "C"`'s so the symbols are mangled for the other case... something more elegent would be great... but the miniz implementation isn't quite setup for it...

**Comment by SoylentGraham** [comment]
Already generally covered, need to modify this repository (I wanted to use it as a submodule) for this situation #93 #94

**Comment by kuba--** [comment]
@SoylentGraham - yes, I have to upgrade miniz, some day (it will also add zip64 support).
Unfortunately it's kind of hacky, right now, because as you can see, this miniz.h was hacked a little bit (with combination of zip.c) to add support for features like merge files/buffers in the fly etc.
