### ISSUE TITLE
Attempting to build from source. No Make file

### ISSUE THREAD

**Issue by seitzcasey** [kuba--/zip#121]
This command seems to succeed.
cmake -DBUILD_SHARED_LIBS=true ..

Attempting to call
make
after results in
make: *** No targets specified and no makefile found.  Stop.

**Comment by codylico** [comment]
Specify a generator?
```bash
cmake -DBUILD_SHARED_LIBS=true .. -G'Unix Makefiles'
```

**Comment by seitzcasey** [comment]
I get this error
No CMAKE_C_COMPILER could be found.

Previously, it defaulted to Visual Studio 16 2019

When I run 
cmake -DBUILD_SHARED_LIBS=true ..
this is the output
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.25.28611.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.18 (a1b07ad0e92e4526c9ba1711d39f06b58c2a7459)") found components: doxygen missing components: dot
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/seitz/Downloads/zip-master/build

**Comment by codylico** [comment]
It looks like CMake is targeting your Visual Studio install. In that case, Cmake will make (i think) a `*.vsproj` file somewhere in `C:/Users/seitz/Downloads/zip-master/build`, which you would open in Visual Studio for building and making. 

Do you have `make` installed on your system somewhere, like maybe in a MinGW or something?

**Comment by seitzcasey** [comment]
Ok you're right. I was able to build in Visual Studio. One issue though is it says it's not able to find zip.lib

**Comment by kuba--** [comment]
Did you check your `C:/Users/seitz/Downloads/zip-master/build`
Maybe check github workflows file (how it's build and tested on windows)
Is it still issue for you, or we can close it?

**Comment by codylico** [comment]
I looked at the source code again. It looks like none of the `zip_...` functions have Windows-style export attributes (that's the `__declspec(dllimport)` thing usually wrapped in a `..._API` macro). Without that, Visual Studio won't produce a `.lib` file.

**Comment by kuba--** [comment]
Ok, makes sense to me to add `__declspec` attributes for shared libraries for `_MSC_VER`. 
I'll find a spare cycle and send PR soon.

**Comment by kuba--** [comment]
Take a look into PR: https://github.com/kuba--/zip/pull/122

I didn't add any of `__declspec(dllimport)/__declspec(dllexport)`, but I've upgraded cmake to 3.4 so you can pass
```
-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE  -DBUILD_SHARED_LIBS=TRUE
```
It can _Create dlls on Windows without `declspec()`_ (more details you can read here: https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/)

Just in case it will also generate `zip_export.h` file 

Let me know if it works for you, so I can cut a new release.

**Comment by kuba--** [comment]
@codylico - I've merged the PR: https://github.com/kuba--/zip/pull/122
So you can check if master branch works for you.

**Comment by codylico** [comment]
@kuba-- I shall check the master branch later today or tomorrow, when I get the chance.

**Comment by codylico** [comment]
Finally got it to work in Visual Studio 2019. As you stated, need both `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` and `-DBUILD_SHARED_LIBS=TRUE`. I used Visual Studio's built-in CMake.

**Comment by kuba--** [comment]
Cool, I'm gonna close this issue, and cut a new release
