### ISSUE TITLE
Expose a function that opens an archive that is already loaded in memory.

### ISSUE THREAD

**Issue by luauser32167** [kuba--/zip#126]
```zip_open``` works only for archives that come from the file system.

**Comment by jinfeihan57** [comment]
@kuba-- 
I want to help to solve this issue.
Do you have a name about this new API ？
I think zip_extract() also needs a similar interface.

**Comment by kuba--** [comment]
In `libzip` there are functions like `zip_open_from_source`. I thought we can take it as kind of standard (I think _source_ or _stream_ sounds more generic than _memory_), but I would make it shorter, e.g. `zip_open_source` or `zip_open_fromsource`, `zip_open_stream`, `zip_extract_stream`, ...

**Comment by jinfeihan57** [comment]
I will take zip_open_stream() and zip_extract_stream().
If there's any change, we can revising it.
