### ISSUE TITLE
Beginner's questions: I don't know how properly store files inside the zip file

### ISSUE THREAD

**Issue by hmslima** [kuba--/zip#127]
I am working in a software that I need to store some HTML and JPG files inside a ZIP file _(actually I am aiming to make an EPUB file)_. I find your software amazing and it seems to fit my needs, but I am finding some difficulties because of my newbieness. Firstly, here is my code:

```
#include <stdio.h>
#include "zip.h"

int main(int argc, char *argv[])
{
	struct zip_t *zip = zip_open("foo.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
	{
		zip_entry_open(zip, "x.jpg");
		{
			zip_entry_fwrite(zip, "z.jpg");
			zip_entry_fwrite(zip, "w.png");
		}
		zip_entry_close(zip);
	}
	zip_close(zip);
}
```

1. First, the `x.jpg` file is not added to the ZIP file and the `z.jpg` file is renamed to "x.jpg"...
2. I can't see the file `w.png`, but seems that its "weight" was added to the `x.jpg` file _(which actually is the `z.jpg` file...)_
3. In the case of adding a HTML or image file, what am I supposed to add in the line `const char *buf = "Some data here...\0";`?

**Comment by codylico** [comment]
Here's something to get you going:
```c
{
  zip_entry_open(zip, "x.jpg"); //start a file in the archive
  zip_entry_fwrite(zip, "x.jpg"); //write that file into the archive (note: same "file" name)
  zip_entry_close(zip); //finish the first file
}
```
Then, for example, the next JPEG image:
```c
{
  zip_entry_open(zip, "z.jpg"); //different name of the file in the archive (in this case, "z.jpg")
  zip_entry_fwrite(zip, "z.jpg"); //different external file to write (i.e. store the `z.jpg` image under the "z.jpg" name)
  zip_entry_close(zip); //finish the second file
}
```
Hope this clarifies things somewhat.

**Comment by kuba--** [comment]
@codylico thanks for clarification.

@hmslima - what you've done is basically the first example from readme - where we _merge 3 files into one entry and compress them on-the-fly_.
So instead of having many files (entries) you have merged them as one zip entry.

If you just need compress files separately, you have to:
- open entry
- fwrite file
- close entry

(see above example posted by @codylico

**Comment by hmslima** [comment]
It worked! Thank you very much! Here is the code for those with the same question:

```
#include <stdio.h>
#include "zip.h"

int main(int argc, char *argv[])
{
	struct zip_t *zip = zip_open("foo.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
	{
		zip_entry_open(zip, "x.jpg"); //start a file in the archive
		zip_entry_fwrite(zip, "x.jpg"); //write that file into the archive (note: same "file" name)
		zip_entry_close(zip); //finish the first file

		zip_entry_open(zip, "z.jpg"); //different name of the file in the archive (in this case, "z.jpg")
 		zip_entry_fwrite(zip, "z.jpg"); //different external file to write (i.e. store the `z.jpg` image under the "z.jpg" name)
  		zip_entry_close(zip); //finish the second file

  		zip_entry_open(zip, "w.png"); //different name of the file in the archive (in this case, "z.jpg")
 		zip_entry_fwrite(zip, "w.png"); //different external file to write (i.e. store the `z.jpg` image under the "z.jpg" name)
  		zip_entry_close(zip); //finish the second file
	}
	zip_close(zip);
}
```
