### ISSUE TITLE
miniz Limitations 

### ISSUE THREAD

**Issue by jinfeihan57** [kuba--/zip#129]
miniz is a Deflate/Inflate compression library.

But zip format include lzma, bzip2 method.
Any interested in adding these two algorithms? 

If Yes : I want to help.

**Comment by kuba--** [comment]
Thanks @jinfeihan57. 
Frankly speaking, if I find some spare time, I'd like to have full 64-bit support, so this is what I'm focused on.
But any PR is very welcome!

**Comment by jinfeihan57** [comment]
@kuba-- 

If add new compress method, I will introduce some new algorithm files. 
I hope that's OK. if so I'll start working in my spare time.

**Comment by kuba--** [comment]
yeah, it's fine if we keep API in zip.[h.c] files files and all the new/private implementation will go to the new file.

**Comment by jinfeihan57** [comment]
> Thanks @jinfeihan57.
> Frankly speaking, if I find some spare time, I'd like to have full 64-bit support, so this is what I'm focused on.
> But any PR is very welcome!

The [miniz](https://code.google.com/archive/p/miniz/) still not support deflate64. 
Is that mean you will implement deflate64 by yourself？

**Comment by kuba--** [comment]
I didn't start seriously working on this, I will have to take a look what has been changed in miniz  _v2_ functions

**Comment by kuba--** [comment]
I'm closing this one (so far). We can reopen if needed.
