### ISSUE TITLE
zip folder into archive

### ISSUE THREAD

**Issue by lukvermeulen** [kuba--/zip#135]
awesome library so far! I wondered how I can make a .zip out of a folder with subfolders and files. Basically the opposite of the example "extract archive into folder". Thanks for any pointers!

**Comment by kuba--** [comment]
@lukvermeulen thanks.
There is no API to compress folders recursively, you have to write your own `walk` function, e.g.:
```c
#include <assert.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

#include <zip.h>

int is_dir(const char *path) {
  struct stat s;
  stat(path, &s);
  return S_ISDIR(s.st_mode);
}

void zip_walk(struct zip_t *zip, const char *path) {
  DIR *dir;
  struct dirent *entry;
  char fullpath[MAX_PATH];

  memset(fullpath, 0, MAX_PATH);
  dir = opendir(path);
  assert(dir);

  while ((entry = readdir(dir))) {
    // skip "." and ".."
    if (!strcmp(entry->d_name, ".\0") || !strcmp(entry->d_name, "..\0"))
      continue;

    snprintf(fullpath, sizeof(fullpath), "%s/%s", path, entry->d_name);
    if (is_dir(fullpath))
      zip_walk(zip, fullpath);
    else {
      zip_entry_open(zip, fullpath);
      zip_entry_fwrite(zip, fullpath);
      zip_entry_close(zip);
    }
  }

  closedir(dir);
}
```

be careful on symbolic links ;-)

**Comment by kuba--** [comment]
BTW, I've updated README, adding a new example ^^^^

**Comment by jinfeihan57** [comment]
@kuba-- 
What if the folder is empty?

**Comment by kuba--** [comment]
it's up to you, you can create an empty entry, this is just an example

**Comment by lukvermeulen** [comment]
Thanks alot for the example @kuba-- ! I am transfering the logic to UE4 - which worked great so far. The only thing is - my code results in one zip folder with _all_ files from the original folder + subfolders(so without the folder hierarchy. Is there something I missed? Or how could I create sub-folder-entries in the zip to have the same folder structure in the zip archive. Thanks!

**Comment by lukvermeulen** [comment]
Thanks alot for the awesome example! It helped me understand how this works and transfer the logic to unreal 4.

**Comment by kuba--** [comment]
@lukvermeulen 
after decompress you should have all files inside subfolders (not a flat structure), so you should check your unzip tool.
take a look into https://github.com/kuba--/zip/issues/132
