### ISSUE TITLE
how to support password?

### ISSUE THREAD

**Issue by xiaodingding** [kuba--/zip#138]
如何加密文件
How to encrypt files

**Comment by kuba--** [comment]
it's not possible (so far), to protect zip files with password.

**Comment by jinfeihan57** [comment]
> 如何加密文件
> How to encrypt files

you can try this project https://github.com/szcnick/p7zip

**Comment by kuba--** [comment]
I'm closing this one because, so far I don't have plans to support passwords. We can reopen this issue in the future

**Comment by parcool** [comment]
Same requirement，I need encryption to!!!
