### ISSUE TITLE
Add compress/decompress string

### ISSUE THREAD

**Issue by pavel-pimenov** [kuba--/zip#141]
https://gist.github.com/yfnick/6ba33efa7ba12e93b148

**Comment by kuba--** [comment]
We have something like that: https://github.com/kuba--/zip/blob/master/src/zip.h#L333

**Comment by kuba--** [comment]
@pavel-pimenov ping ^^^

**Comment by kuba--** [comment]
@pavel-pimenov I'm closing this issue, right now. 
If you have any questions or new stream API does not work for you, you can always re-open the issue.
