### ISSUE TITLE
MinGW fails compilation

### ISSUE THREAD

**Issue by nick-dumas** [kuba--/zip#145]
Reproducing on windows 10:
1. Install MinGW-get from https://osdn.net/projects/mingw/releases/p15522
2. Add the mingw32-base-bin and mingw-gcc-g++-bin packages.
2. Install cmake.
3. Add C:\MinGW\bin to path.
4. `mkdir build`, `cmake .. -G "MinGW Makefiles"`, `cmake --build .`
[error.log](https://github.com/kuba--/zip/files/5524788/error.log)

Relevant MinGW header:
(https://sourceforge.net/p/mingw/mingw-org-wsl/ci/21762bb4a1bd0c88c38eead03f59e8d994349e83/tree/include/sys/types.h)

MinGW doesn't use any defines to indicate ssize_t has been declared. I suggest we detect MinGW directly.
After adding a check for __MINGW32__ before the ssize_t typedef, it compiles and passes `mingw32-make test`.
[patch.txt](https://github.com/kuba--/zip/files/5524735/patch.txt)
I'll create a PR if this looks OK.

**Comment by kuba--** [comment]
... but if you take a look into your types.h:
```

#ifndef _SSIZE_T_
#define _SSIZE_T_
typedef int _ssize_t;
```

we can check this macro

**Comment by kuba--** [comment]
@nick-dumas - as you can see (on the master branch), I've added `windows-mingw32` build and it compiles without any issues.

**Comment by nick-dumas** [comment]
Thanks @kuba--! It still isn't working unfortunately. Here's more info on my machine while I look further into it.
![image](https://user-images.githubusercontent.com/48195388/99064310-c270b380-25e0-11eb-8dad-9cb7ab5a1621.png)
I'm currently finding the repo that my header been fetched from.
[types.h](https://github.com/kuba--/zip/files/5536286/types.h.txt)

**Comment by jinfeihan57** [comment]
What's your Mingw version?

**Comment by jinfeihan57** [comment]
@nick-dumas Do you have another compiler tools？like vs_studio or cygwin.move the mingw environment variable to the foremost or delete other compiler environment variables temporarily.

**Comment by kuba--** [comment]
> Thanks @kuba--! It still isn't working unfortunately. Here's more info on my machine while I look further into it.
> ![image](https://user-images.githubusercontent.com/48195388/99064310-c270b380-25e0-11eb-8dad-9cb7ab5a1621.png)
> I'm currently finding the repo that my header been fetched from.
> [types.h](https://github.com/kuba--/zip/files/5536286/types.h.txt)

Ok, so if you take a look into your `types.h` file, seems we need to add another macro `__have_typedef_ssize_t`

**Comment by nick-dumas** [comment]
My version is 0.6.3-pre-20170905-1.
![image](https://user-images.githubusercontent.com/48195388/99066627-395b7b80-25e4-11eb-90fa-e5ac3d8707f5.png)
I'll look into this further on the weekend when I have a bit more time, and see if I can find the difference between the validation build and local. 
The actual compilation failure occurs because of conflicting types, which might not happen with a 32 bit environment or something weird like that.

**Comment by kuba--** [comment]
I've merged the new macro, PTAL.
https://github.com/kuba--/zip/pull/147

**Comment by jinfeihan57** [comment]
Have some issue on here? if don't have macro: __have_typedef_ssize_t in file [types.h](https://github.com/kuba--/zip/files/5536286/types.h.txt) line 123 will  typedef _ssize_t  ssize_t; that means zip.h don't need to define ssize_t. But if have macro __have_typedef_ssize_t . it's seem like the environment have ssize_t.
 I think here we need a macro to identifies his environment.

**Comment by kuba--** [comment]
> Have some issue on here? if don't have macro: __have_typedef_ssize_t in file [types.h](https://github.com/kuba--/zip/files/5536286/types.h.txt) line 123 will typedef _ssize_t ssize_t; that means zip.h don't need to define ssize_t. But if have macro __have_typedef_ssize_t . it's seem like the environment have ssize_t.
> I think here we need a macro to identifies his environment.

It's already merged, see ^^^^

**Comment by nick-dumas** [comment]
#### I've done some more research around the issue
The github CI uses [Mingw-w64 8.1.0](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md), and the failure occurs on [MinGW](http://www.mingw.org/). The types.h header hasn't changed ssize_t stuff since mingwrt-3.21.1, 2015-06-08. 
I've had another search, and the file [here](https://osdn.net/projects/mingw/scm/git/mingw-org-wsl/blobs/5.4-trunk/mingwrt/include/sys/types.h) matches the one on my system (Checked with diff). 
#### About the implemented patch
Unfortunately, `__have_typedef_ssize_t` is only defined if `__GNUC__ < 4`, which isn't the case.
I agree with the comment that we'll need a macro to identify the environment. I suggest `__MINGW32__`.
#### I've also started looking into a build test
We'd need to [download and install MinGW](http://www.mingw.org/wiki/InstallationHOWTOforMinGW).

It also looks like Mingw-w64 has better compatibility, so I'll be using that anyway.

**Comment by kuba--** [comment]
> Unfortunately, `__have_typedef_ssize_t` is only defined if `__GNUC__ < 4`, which isn't the case.
> I agree with the comment that we'll need a macro to identify the environment. I suggest `__MINGW32__`.
> 

Frankly speaking, I'd like to find the correct macro for _your_ `mingw32` version and `ssize_t`.
Using `__MINGW32__` just for `ssize_t` is too generic (IMO). It means that all mingw32 versions and compilers implement/define `ssize_t`, what I think may not be correct.

**Comment by jinfeihan57** [comment]
> I'd like to find the correct macro for _your_ `mingw32` version and `ssize_t`.
@nick-dumas Can you run CMD " echo | gcc -E -dM - | sort "  on your environment?

**Comment by nick-dumas** [comment]
Please see [here](https://github.com/kuba--/zip/files/5554091/gcc_define.txt) for gcc inbuilt defines.
You might find [_mingw.h](https://github.com/kuba--/zip/files/5554102/_mingw.h.txt) more useful. It is included by types.h and contains the version definitions. It's created from [_mingw.h.in](https://osdn.net/projects/mingw/scm/git/mingw-org-wsl/blobs/5.4-trunk/mingwrt/include/_mingw.h.in). You're probably interested in:
```
#define __MINGW32_VERSION           5004001L
#define __MINGW32_MAJOR_VERSION           5
#define __MINGW32_MINOR_VERSION           4
#define __MINGW32_PATCHLEVEL              1
```

**Comment by kuba--** [comment]
we need to find what macro is defined for ssize_t typedef

**Comment by nick-dumas** [comment]
As far as I'm aware, there isn't any.

**Comment by kuba--** [comment]
Ok, I think we can check:
```
#if !(defined _POSIX_C_SOURCE)
```

**Comment by jinfeihan57** [comment]
@kuba-- 
I think we can try :
#if (defined(__MINGW32__) && !defined(__MINGW64__)) 
to identify his environment.

**Comment by kuba--** [comment]
To recap... 
_defines_ of `ssize_t` were generally added for MSVC compiler on windows, where we don't have POSIX support.
I walked through our commits and _type_ headers and I believe it can be simplified just to:
https://github.com/kuba--/zip/pull/148

Hopefully thanks to this PR we won't have to worry about _yet another missing macro_.

PTAL.

**Comment by nick-dumas** [comment]
Good news!
Branch nodef-ssize_t, git commit 750078c build and test succeeds.
```console
PS C:\Users\nicho\Downloads\zip\build> mingw32-make test
Running tests...
"C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process
Test project C:/Users/nicho/Downloads/zip/build
    Start 1: test.out
1/1 Test #1: test.out .........................   Passed    9.27 sec

100% tests passed, 0 tests failed out of 1                                                                                                                                                                                                                                                  

Total Test time (real) =   9.34 sec
```
