### ISSUE TITLE
How to create a new archive in memory?

### ISSUE THREAD

**Issue by folibis** [kuba--/zip#153]
`zip_open` requires a filename to be saves in a local filesystem. What if I what to create an archive in the memory, without saving it in a local filesystem, to send it over network, for example?

**Comment by codylico** [comment]
`zip_open_stream`?

**Comment by kuba--** [comment]
So far, it's possible to read/extract zip archive from the memory/stream by `zip_open_stream`, but there is no API to create and save a new zip archive into the memory stream.

**Comment by folibis** [comment]
I've meant to do something like this:
```
struct zip_t *zip = zip_open_memory(ZIP_DEFAULT_COMPRESSION_LEVEL);
{
    zip_entry_open(zip, "foo-1.txt");
    {
        const char *buf = "Some data here...\0";
        zip_entry_write(zip, buf, strlen(buf));
    }
    zip_entry_close(zip);
}
char *data = zip->data();
send_data_over_network(data);

zip_close(zip);
```
i.e. how to create and manipulate an archive in the memory?

it looks like `zip_open_stream` is intended for reading an existing archive into the memory, at least `const char *stream` a bit confuses me.

**Comment by kuba--** [comment]
Yes, I understand your use case. So, for writing it's not done, yet. Unfortunately, right now the simplest workaround  is to go through temporary file, read all and delete the temp. file.

**Comment by jinfeihan57** [comment]
@folibis 
The usage can be found in test.
You can test it.

**Comment by kuba--** [comment]
@folibis - I think the new stream API (zip_open_stream, zip_close_stream, zip_copy_stream) will work for you, so we can close this issue. PTAL.
