### ISSUE TITLE
Issue found in normalize()

### ISSUE THREAD

**Issue by IgorJorobus** [kuba--/zip#157]
Hello kuba & collabs,

I'm trying to unzip an empty *.xlsx file (which is a masked *.zip file) and am not being able. FYI I'm able to unzip the file with 7-zip and the built-in Windows unzipper.

I did some debugging, and found the problem. It looks like the library finds a file to unzip that actually _doesn't exist_. The path string of this _supposed file_ is `"_rels/"`. `"s4cc"` is the folder where the zip gets unzipped.

![image](https://user-images.githubusercontent.com/1852056/102460281-89838e80-4025-11eb-8973-49cface7502f.png)

This is how the unzipping should look like inside of _s4cc_ folder (done this with 7-zip):

![image](https://user-images.githubusercontent.com/1852056/102460485-cd769380-4025-11eb-9b8b-6ec9011a4c55.png)

Inside __rels_ we have a _.rels_ file:

![image](https://user-images.githubusercontent.com/1852056/102465454-6c05f300-402c-11eb-83d0-6d62a8a1395e.png)

As you can see, there's no `"_rels/"` file, also, you can't have "/" as part of a file name. I inquired further and the problem starts here:

![image](https://user-images.githubusercontent.com/1852056/102461241-e03d9800-4026-11eb-83a2-70a4ebbf2f01.png)

`info.m_filename` brings `"_rels/"`.

Looking further, there's a _normalize()_ function call some lines above (940) that modifies `info.m_filename`. I went into this function and found exactly where the problem is:

![image](https://user-images.githubusercontent.com/1852056/102465899-ffd7bf00-402c-11eb-973c-f76ed055786a.png)

After this line, `nname[6]` will be replaced by `'\0'` and there the string will be cutted, bringing the normalized name to `"_rels/"`. That's where the problem begins and of course brings a cascade of problems. I won't provide a fix for this because I don't really know what is the purpose of that check there on line 890.

**Development & target system**: Windows x32 & x64
**Compiler**: MinGW gcc 9.2.0
**Library version**: tested with 0.1.11 & 0.1.20

I'm attaching the zip. Let me know if you need any other help. Thanks in advance.

[sample.zip](https://github.com/kuba--/zip/files/5708198/sample.zip)

Best regards,

D.

**Comment by kuba--** [comment]
Thanks, I'll take a look. But generally zip extracts archive using relative (not absolute) path.
So, it should put all files and directories in your local directory.  This is what `zipinfo` prints:
```
zipinfo sample.zip
Archive:  sample.zip
Zip file size: 7629 bytes, number of entries: 9
-rw----     4.5 fat     1032 b- defS 80-Jan-01 00:00 [Content_Types].xml
-rw----     4.5 fat      588 b- defS 80-Jan-01 00:00 _rels/.rels
-rw----     4.5 fat      557 b- defS 80-Jan-01 00:00 xl/_rels/workbook.xml.rels
-rw----     4.5 fat     1159 b- defS 80-Jan-01 00:00 xl/workbook.xml
-rw----     4.5 fat     1457 b- defS 80-Jan-01 00:00 xl/styles.xml
-rw----     4.5 fat     6798 b- defS 80-Jan-01 00:00 xl/theme/theme1.xml
-rw----     4.5 fat      644 b- defS 80-Jan-01 00:00 xl/worksheets/sheet1.xml
-rw----     4.5 fat      619 b- defS 80-Jan-01 00:00 docProps/core.xml
-rw----     4.5 fat      785 b- defS 80-Jan-01 00:00 docProps/app.xml
```

**Comment by kuba--** [comment]
...and following code prints stuff correctly:
```
struct zip_t *zip = zip_open("sample.zip", 0, 'r');
int i, n = zip_total_entries(zip);
for (i = 0; i < n; ++i) {
    zip_entry_openbyindex(zip, i);
    {
        const char *name = zip_entry_name(zip);
        int isdir = zip_entry_isdir(zip);
        unsigned long long size = zip_entry_size(zip);
        unsigned int crc32 = zip_entry_crc32(zip);
	printf("%s %d %llu %u\n", name, isdir, size, crc32);
    }
    zip_entry_close(zip);
}
zip_close(zip);
```

... but I'll take a look what's wrong with extract method. Of course something can be wrong in `normalize` function.

**Comment by kuba--** [comment]
@IgorJorobus -  I think the problem is in the code where you pointed we use `strncmp`, and we compare only **one** character `"."` (to skip "." and ".." directories). Unfortunately here it skips files which starts with ".", e.g `.rels`.

Anyway, I'm gonna fix it, but looks like replacing `strncmp`, but regular `strcmp` may solve the problem.

**Comment by kuba--** [comment]
You can take a look if PR: https://github.com/kuba--/zip/pull/159
fixes the issue for you.

**Comment by IgorJorobus** [comment]
Hi kuba. Yes, the PR fixes the problem. Thanks for the quick fix. Cheers!
