### ISSUE TITLE
The 'pZip' pointer was utilized before it was verified against nullptr

### ISSUE THREAD

**Issue by pavel-pimenov** [kuba--/zip#16]
V595 The 'pZip' pointer was utilized before it was verified against nullptr. Check lines: 4424, 4433. miniz.h 4424

![default](https://user-images.githubusercontent.com/920705/32591713-974598c8-c531-11e7-8a79-9f31dcd86305.png)

**Comment by kuba--** [comment]
@pavel-pimenov thanks - I've sent a PR: https://github.com/kuba--/zip/pull/17

**Comment by kuba--** [comment]
already merged
