### ISSUE TITLE
Support for PIC32

### ISSUE THREAD

**Issue by NiJagadish** [kuba--/zip#163]
Does this code base support PIC32.....

I found the error related to some of the files as given below.....,
#include <sys/stat.h> was not found...... and same for the related files..... 

Could you please help me out...?

**Comment by jinfeihan57** [comment]
what do you mean? PIC microcontrollers?

**Comment by kuba--** [comment]
@NiJagadish `sys/stat.h` is a POSIX header and we mainly support POSIX systems. Looks like your controller does not fully implement POSIX. 
Probably other headers also are missed. 

So far, I do not have any plans to support/be compatible with microcontrollers, but any PR is welcome!

**Comment by NiJagadish** [comment]
> what do you mean? PIC microcontrollers?

Yes.

**Comment by NiJagadish** [comment]
> @NiJagadish `sys/stat.h` is a POSIX header and we mainly support POSIX systems. Looks like your controller does not fully implement POSIX.
> Probably other headers also are missed.
> 
> So far, I do not have any plans to support/be compatible with microcontrollers, but any PR is welcome!

Okay... 
thank you....
