### ISSUE TITLE
Library related warnings when compiling

### ISSUE THREAD

**Issue by damian-m-g** [kuba--/zip#164]
Hello kuba & supporters,

I'm wondering if the issues the warnings point when compiling are affecting somehow my code:

![image](https://user-images.githubusercontent.com/1852056/103439067-8b01a900-4c18-11eb-8061-cb869b2877dc.png)

It's as if the IDE/compiler can't find where those functions are declared.

Development & target system: Windows x32 & x64
Compiler: MinGW gcc 9.2.0
Library version: 0.1.21

**Comment by kuba--** [comment]
This is kind of tricky, because documentation says that functions like `_wfopen_s` are defined either in `stdio.h` or `wchar.h`.
And as you can see `stdio.h` is already included in `miniz.h:4113`.

I wonder if it can be related how MinGW was installed.

**Comment by IgorJorobus** [comment]
Probably is that. I tried yesterday to compile with msys/mingw gcc that comes with one of the last Ruby versions for Windows, which is version 10.2.0 (versus 9.2.0 that comes with MinGW official website), and the warnings went gone. It looks like indeed those warnings were bothering the compiling of my DLL because couldn't call it from another app, while compiling with 10.2.0 has no issues.

**Comment by IgorJorobus** [comment]
This is the output for the **msys/mingw gcc** that comes with Ruby windows installer (no warnings are thrown when compiling with this):

![image](https://user-images.githubusercontent.com/1852056/103459650-a68bb300-4cef-11eb-87a5-2aebb02d668a.png)

This is the output for the **mingw gcc** compiler, downloaded from MinGW official website (warnings thrown):

![image](https://user-images.githubusercontent.com/1852056/103459724-f0749900-4cef-11eb-9420-f8d9dbc6693d.png)

**Comment by kuba--** [comment]
looks that the main difference here is gcc 9.2 vs gcc 10.2

**Comment by kuba--** [comment]
> looks that the main difference here is gcc 9.2 vs gcc 10.2

maybe you need to define `MINGW_HAS_SECURE_API` for your distribution. to have `_w` functions

**Comment by IgorJorobus** [comment]
FYI: I tried your last suggestion with 9.2 and didn't work. Same warnings.
