### ISSUE TITLE
zip_extract() returns 0 (OK) even if can't find ZIP

### ISSUE THREAD

**Issue by IgorJorobus** [kuba--/zip#165]
Hello kuba & collabs,

I use the return code of zip_extract() to find out if successfully extract files. When you pass a non-existent path to a zip, it will return 0 while it shouldn´t? Maybe I'm missing some thinking approach here, I'm basing on the zip_extract() documentation that says: _0 on success, negative number (< 0) on error_.

![image](https://user-images.githubusercontent.com/1852056/103440831-a58f4e80-4c27-11eb-86cf-0243e734b30b.png)

From my point of view, it shouldn't return 0 if can't find the zip archive.

Cheers,

D.

**Comment by kuba--** [comment]
Thanks, it should be fixed by https://github.com/kuba--/zip/pull/166

**Comment by IgorJorobus** [comment]
The commit looks good. Thank you.
