### ISSUE TITLE
zip_entry_write capturing nothing out of my const char

### ISSUE THREAD

**Issue by x64debug** [kuba--/zip#168]
Hello, I am wondering why this was not working

**Comment by kuba--** [comment]
@x64debug - I need more context.  What does it mean - "not working"? The partial snippet does not explain much.

As an example I created following file `main.cpp`:
```C
#include <cstdio>
#include <string>
#include <zip.h>

int main() {
	std::string str("this is test string");
	const char *buf = str.c_str();
	int len = strlen(buf);

	zip_t *z = zip_open("/tmp/main.zip", 5, 'w');
	zip_entry_open(z, "test.txt");
	zip_entry_write(z, buf, len);
	zip_entry_close(z);
	zip_close(z);
	return 0;
}
```

And I compiled: `g++ -I../src libzip.a main.cpp -o main`

It works fine for me. If it does not for you, please give more context.

**Comment by x64debug** [comment]
My string has multiple lines in it like Hi\nHello\n and it seems like only the first line shows up when put in a txt in the zip

**Comment by kuba--** [comment]
> My string has multiple lines in it like Hi\nHello\n and it seems like only the first line shows up when put in a txt in the zip

Without any details, it's hard to help, but I don't see any problems with multiline strings.

```bash
cd build
cmake ..
make

cat main.cpp
```
```c
#include <cstdio>
#include <string>
#include <zip.h>

int main() {
	std::string str("the first line\nthis is the second line\n...and the third one");
	const char *buf = str.c_str();
	int len = strlen(buf);


	zip_t *z = zip_open("/tmp/test.zip", 5, 'w');
	zip_entry_open(z, "test.txt");
	zip_entry_write(z, buf, len);
	zip_entry_close(z);
	zip_close(z);
	return 0;
}
```

```bash
g++ -Wall -I../src libzip.a main.cpp -o main
./main
unzip /tmp/test.zip
cat test.txt 

the first line
this is the second line
...and the third one
```

**Comment by x64debug** [comment]
Oh sorry I was doing it wrong 🤦

**Comment by x64debug** [comment]
Does zip_open automatically created temp file?

**Comment by x64debug** [comment]
I apologize, is it possible to zip an existing folder?

**Comment by kuba--** [comment]
> I apologize, is it possible to zip an existing folder?

There is no API like _zip folder_. You have to write some code to do that, but if you take a look into `README.md` file, there is a section _Compress folder (recursively)_ with example.
