### ISSUE TITLE
zip stream API

### ISSUE THREAD

**Issue by kuba--** [kuba--/zip#169]
@jinfeihan57
I just realized that we have:

`zip_open`, `zip_close`
`zip_entry_open`, `zip_entry_close`, `zip_entry_write`, etc.

but we have `zip_open_stream`, `zip_close_stream`, `zip_extract_stream`, `zip_copy_stream`, ...

and I think it does not look logical, because we had:

`zip_[type]_<operation>`, like `zip_entry_open`, but for stream we have `zip_<operation>_<type>`.

What do you think to change API (I hope it's not late) and follow the convention like we have for entries, so it will be:
`zip_stream_...`

**Comment by jinfeihan57** [comment]
This is really confusing, my fault.
I think it is more reasonable to use your original naming rule zip_[type]_<operation>.
I will make changes on a new branch.

**Comment by jinfeihan57** [comment]
@kuba-- 
Please check this PR. #170
