### ISSUE TITLE
investigate codecov security incident

### ISSUE THREAD

**Issue by rikogeln** [kuba--/zip#181]
We got notified of a breach in the codecov service and this project could also be affected see:https://about.codecov.io/security-update/ and if applicable please follow the mitigation steps there and make sure the zip source code has not been compromised. 

Most likely you are already aware of this - but i wanted to flag it just to be on the safe side.

**Comment by kuba--** [comment]
Thanks @rikogeln - `zip` does not use codecov (it used long time ago). Anyway, I just in case I removed access for codecov app.
