### ISSUE TITLE
Is there a way to inflate only one chunk at a time?

### ISSUE THREAD

**Issue by bloomen** [kuba--/zip#182]
Thanks for the neat library!

I was wondering if it's possible to inflate only one chunk at a time? Or do I need to decompress the entire zip file?

**Comment by kuba--** [comment]
Thanks,
@bloomen - do you mean extract just one entry?
For instance you have a `foo.zip` which contains `foo-1.txt, foo-2.txt, ..., foo-n.txt` and you want to just extract `foo-2.txt`. 
If this is your use case, then it's as simple as (if you want to save to file):

```c
struct zip_t *zip = zip_open("foo.zip", 0, 'r');
{
    zip_entry_open(zip, "foo-2.txt");
    {
        zip_entry_fread(zip, "foo-2.txt");
    }
    zip_entry_close(zip);
}
zip_close(zip);
```

or (if you want to extract in memory)

```
void *buf = NULL;
size_t bufsize;

struct zip_t *zip = zip_open("foo.zip", 0, 'r');
{
    zip_entry_open(zip, "foo-2.txt");
    {
        zip_entry_read(zip, &buf, &bufsize);
    }
    zip_entry_close(zip);
}
zip_close(zip);
```

**Comment by bloomen** [comment]
I've seen these code snippets and they work fine but what I need is to inflate just the first n bytes or chunks of an entry. Is that possible?

**Comment by kuba--** [comment]
Ohh, ok.
In theory it's not supported, but you can try with callback (maybe it will work for you), e.g.:
```c
struct buffer_t {
    char *data;
    size_t size;
};

static size_t on_extract(void *arg, unsigned long long offset, const void *data, size_t size) {
    struct buffer_t *buf = (struct buffer_t *)arg;
    buf->data = realloc(buf->data, buf->size + size + 1);
    assert(NULL != buf->data);

    memcpy(&(buf->data[buf->size]), data, size);
    buf->size += size;
    buf->data[buf->size] = 0;

    return size;
}

struct buffer_t buf = {0};
struct zip_t *zip = zip_open("foo.zip", 0, 'r');
{
    zip_entry_open(zip, "foo-1.txt");
    {
        zip_entry_extract(zip, on_extract, &buf);
    }
    zip_entry_close(zip);
}
zip_close(zip);
```

So, in your callback function `on_extract` you can skip some bytes or if you're done, you can try to return `0`.
Most likely `zip_entry_extract` will get an error, but at least you can memorize the chunk.

In other words, if you return _incorrect_ size from the callback, you'll break the extracting process.

**Comment by kuba--** [comment]
@bloomen - does the workaround (☝🏻 ) work for you?

**Comment by kuba--** [comment]
By the way, I wrote example and I think it may work for you. Basically it populates a buffer by data rom `foo-1.txt`. It starts with `buf.off` up to `buf.cap`.
Take a look:

```c
#include <stdio.h>
#include <stdlib.h>
#include <zip.h>

struct buffer_t {
    char *data;
    size_t off;
    size_t size;
    size_t cap;
};

static size_t on_extract(void *arg, unsigned long long offset, const void *data, size_t size) {
       struct buffer_t *buf = (struct buffer_t *)arg;

	printf("\t offset: %lld, size: %ld, data: %s\n", offset, size, data);

	size_t off = 0;
	size_t len = buf->cap - buf->size;
	if (len == 0) {
		return 0;
	}

	if (len > size) {
		len = size;
	}

	if (offset >= buf->off) {
		off = 0;
	} else if (buf->off < offset + size) {
		off = buf->off - offset;
	} else {
		return size;
	}

        memcpy(&(buf->data[buf->size]), &data[off], len);
        buf->size += len;
        return len;
}

int main() {

struct buffer_t buf;
buf.off = 5;
buf.size = 0;
buf.cap = 10;
buf.data = (char *)calloc(1 + buf.cap, sizeof(char));

struct zip_t *zip = zip_open("foo.zip", 0, 'r');
{
    zip_entry_open(zip, "foo-1.txt");
    {
        zip_entry_extract(zip, on_extract, &buf);
    }
    zip_entry_close(zip);
}
zip_close(zip);

printf("buf.data: '%s'\n", buf.data);
free(buf.data);

return 0;
}
```

**Comment by bloomen** [comment]
Thanks for the example! I'll give it a go on my end. What is the chunk size that `on_extract` is called with? Is it always the same, hard coded somewhere in the library?

**Comment by bloomen** [comment]
I just tested this and it seems that `on_extract` is only called once with the full size of the entry.

**Comment by kuba--** [comment]
It depends (mostly 32K). Probably you tried with some small file. For instance with 1GB file I get:
```
         offset: 0, size: 32768
         offset: 32768, size: 32758
         offset: 65526, size: 10
         offset: 65536, size: 32768
         offset: 98304, size: 32748
...
```

**Comment by bloomen** [comment]
I see. Thanks for your help!

**Comment by duckbill007** [comment]
@kuba-- Hi, it seems that your example has a bug.
For example -we need 1Mb of data, starting from 1024.
Callback gets first chunk of length 32K
In this case we got: len = 1M (at first)
len(1Mb) > size(32K), so len = size.

off = 1024,
and we are trying to memcpy of 32K data from offset 1024 and go outside of source buffer.

**Comment by kuba--** [comment]
@duckbill007 - yep, you're right, we need to subtract `off` from the `len`. I've fixed the example ☝🏻.
Thanks.
