### ISSUE TITLE
New release 0.1.31?

### ISSUE THREAD

**Issue by jgsogo** [kuba--/zip#185]
Hi!

We are packaging this library in ConanCenter (https://github.com/conan-io/conan-center-index/pull/5081). While working on it, we submitted upstream some fixes to the build-system that are already merged (https://github.com/kuba--/zip/pull/178). Is it possible to get a new tag/release so we can package that new version in ConanCenter and avoid adding patches to the Conan recipe that will no longer be needed?

Thanks!

**Comment by kuba--** [comment]
Here you go: https://github.com/kuba--/zip/releases/tag/v0.1.31
