### ISSUE TITLE
Create in-memory ZIP archive

### ISSUE THREAD

**Issue by Tectu** [kuba--/zip#188]
It would be great to have a way to create a ZIP archive in-memory without the need of creating it on the filesystem.

Is this something that is on the roadmap? How difficult would it be to implement this?

**Comment by Tectu** [comment]
Well... seems like `zip_stream_open()` is what I want.

Excuse the noise.

**Comment by kuba--** [comment]
Yep, recently the new _stream_ API was added: `zip_stream_open`, `zip_stream_copy`, `zip_stream_close` which basically does the thing.
