### ISSUE TITLE
undefined reference to `_ftelli64' - MINGW - 

### ISSUE THREAD

**Issue by hsmku** [kuba--/zip#193]
Hello,

I compile under Windows 7 64 bits and i got this undefined reference !
I already added -lws2_32 in linker options !

Please help me !!

**Comment by hsmku** [comment]
I use MINGW-64 for windows with GNU GCC - when I compile for C program, it give me the undefined ref above.
And the 
_I already added -lws2_32 in linker options !_
has nothing to do here (for socket).

I tried to lookup many time on google but I found nothing !!!

Except a hook in `CXFLAGS` to do `-D_ftelli64=_ftello64`

But `_ftello64` is also an undefined reference.

**Comment by hsmku** [comment]
Either I love your library ! EXTREMLY SIMPLE !!!! I LOVE THAT !

**Comment by hsmku** [comment]
Hello : https://fr.osdn.net/projects/mingw/ticket/38225

Legacy WINDOWS does not implement _ftelli64 till msvcr80...

Just replaced _ftelli64 and _fseeki64 by ftell and fseek in miniz.h !!

Works exactly the same !!

THANKS ! This lib is great for microdevices !!!!

**Comment by kuba--** [comment]
Thanks, maybe I'll try to unify some configs, in the future.

**Comment by aicarambazigalo** [comment]
This issue has been encountered in two places:
https://github.com/ziglang/zig/issues/9402
and
https://github.com/MasterQ32/ZigAndroidTemplate/issues/5#issuecomment-909339943

**Comment by kuba--** [comment]
I've just sent PR: https://github.com/kuba--/zip/pull/207 (replacing _ftelli64 and _fseeko64 by ftell and fseek on for MINGW32).
Please let me know if the fix works for you.

**Comment by aicarambazigalo** [comment]
unless I'm misunderstanding something, that PR may not be right currently... as it tries to change something else (`_ftello64`  for example, instead of `_ftelli64`). I'm on Windows 7 Professional 64bit SP1.

In [my particular case](https://github.com/MasterQ32/ZigAndroidTemplate/issues/5#issuecomment-909574651) here's what I've changed (commented out and replaced):
```zig
//#define MZ_FTELL64 _ftelli64
//#define MZ_FSEEK64 _fseeki64
#define MZ_FTELL64 ftell
#define MZ_FSEEK64 fseek
```
and in context they are:
```zig
...
static FILE *mz_freopen(const char *pPath, const char *pMode, FILE *pStream) {
  wchar_t *wPath = str2wstr(pPath);
  wchar_t *wMode = str2wstr(pMode);
  FILE *pFile = _wfreopen(wPath, wMode, pStream);

  free(wPath);
  free(wMode);

  return pFile;
}

#ifndef MINIZ_NO_TIME
#include <sys/utime.h>
#endif
#define MZ_FILE FILE
#define MZ_FOPEN mz_fopen
#define MZ_FCLOSE fclose
#define MZ_FREAD fread
#define MZ_FWRITE fwrite
//#define MZ_FTELL64 _ftelli64
//#define MZ_FSEEK64 _fseeki64
#define MZ_FTELL64 ftell
#define MZ_FSEEK64 fseek
#define MZ_FILE_STAT_STRUCT _stat
#define MZ_FILE_STAT _stat
#define MZ_FFLUSH fflush
#define MZ_FREOPEN mz_freopen
#define MZ_DELETE_FILE remove
#elif defined(__MINGW32__)
#ifndef MINIZ_NO_TIME
#include <sys/utime.h>
#endif
#define MZ_FILE FILE
#define MZ_FOPEN(f, m) mz_fopen
#define MZ_FCLOSE fclose
#define MZ_FREAD fread
#define MZ_FWRITE fwrite
#define MZ_FTELL64 ftell
#define MZ_FSEEK64 fseek
#define MZ_FILE_STAT_STRUCT _stat
#define MZ_FILE_STAT _stat
#define MZ_FFLUSH fflush
#define MZ_FREOPEN(f, m, s) mz_freopen
#define MZ_DELETE_FILE remove
#elif defined(__TINYC__)
#ifndef MINIZ_NO_TIME
#include <sys/utime.h>
#endif
#define MZ_FILE FILE
#define MZ_FOPEN(f, m) fopen(f, m)
#define MZ_FCLOSE fclose
#define MZ_FREAD fread
#define MZ_FWRITE fwrite
#define MZ_FTELL64 ftell
#define MZ_FSEEK64 fseek
#define MZ_FILE_STAT_STRUCT stat
#define MZ_FILE_STAT stat
#define MZ_FFLUSH fflush
#define MZ_FREOPEN(f, m, s) freopen(f, m, s)
#define MZ_DELETE_FILE remove
#elif defined(__GNUC__) && _LARGEFILE64_SOURCE
#ifndef MINIZ_NO_TIME
#include <utime.h>
#endif
#define MZ_FILE FILE
#define MZ_FOPEN(f, m) fopen64(f, m)
#define MZ_FCLOSE fclose
#define MZ_FREAD fread
#define MZ_FWRITE fwrite
#define MZ_FTELL64 ftello64
#define MZ_FSEEK64 fseeko64
#define MZ_FILE_STAT_STRUCT stat64
#define MZ_FILE_STAT stat64
#define MZ_FFLUSH fflush
#define MZ_FREOPEN(p, m, s) freopen64(p, m, s)
#define MZ_DELETE_FILE remove
#else
#ifndef MINIZ_NO_TIME
#include <utime.h>
#endif
#define MZ_FILE FILE
#define MZ_FOPEN(f, m) fopen(f, m)
#define MZ_FCLOSE fclose
#define MZ_FREAD fread
#define MZ_FWRITE fwrite
#if _FILE_OFFSET_BITS == 64 || _POSIX_C_SOURCE >= 200112L
#define MZ_FTELL64 ftello
#define MZ_FSEEK64 fseeko
#else
#define MZ_FTELL64 ftell
#define MZ_FSEEK64 fseek
#endif
#define MZ_FILE_STAT_STRUCT stat
#define MZ_FILE_STAT stat
#define MZ_FFLUSH fflush
#define MZ_FREOPEN(f, m, s) freopen(f, m, s)
#define MZ_DELETE_FILE remove
#endif // #ifdef _MSC_VER
#endif // #ifdef MINIZ_NO_STDIO
...
```

**Comment by aicarambazigalo** [comment]
hmm looks like I've already had a version of `miniz.h` with the change in that PR from https://github.com/MasterQ32/ZigAndroidTemplate/blob/66daf5ae5c9828680e060a5a1f46b35c41537022/vendor/kuba-zip/miniz.h#L4157-L4174

so then, perhaps in addition to that PR, I've had to do the aforementioned 2-line change too.
