### ISSUE TITLE
Type C4244 compiler warnings. 

### ISSUE THREAD

**Issue by UAchar** [kuba--/zip#195]
I get a lot of c4244 compiler warnings with this zip library. Is there a plan to fix them?
![Kuba_Zip_Comiper_Warnings](https://user-images.githubusercontent.com/86720341/123951544-33fd4680-d9a5-11eb-84dc-0c6823527dcc.png)

**Comment by maxsupermanhd** [comment]
Try compiling with MinGW

**Comment by kuba--** [comment]
@UAchar - it's not easy to get rid of all warnings for Windows/MSC and keep backward compatibility on other platforms, but I tried to replace (where it's possible) `mz_uint64` by `size_t`.
PTAL https://github.com/kuba--/zip/pull/196 if you see at least less warnings.
