### ISSUE TITLE
zip_entry_noallocread error

### ISSUE THREAD

**Issue by AtariSMN82** [kuba--/zip#197]
Why i get error code "extracting data using no memory allocation" from zip_entry_noallocread if i use this compiler defines: -DRELEASE -DNDEBUG (GCC 9.2.0, Windows7 x32)

**Comment by kuba--** [comment]
@AtariSMN82 - could you give more context (maybe code)?

The error definitively comes from https://github.com/kuba--/zip/blob/master/src/miniz.h#L5164 function, but I'm trying to understand your use case (how it's different from test case:
https://github.com/kuba--/zip/blob/2f6857e267b0eedee5f2842429172c38c1972a3a/test/test_read.c#L86).

If you don't define macros (RELEASE and/or NDEBUG) then it works for you?

**Comment by AtariSMN82** [comment]
@kuba-- Sorry, this error occurs when i use multi-threaded archive reading. Blocking thread by mutex fix it

**Comment by kuba--** [comment]
Ok, I'm closing this one.
