### ISSUE TITLE
Some more warnings from miniz.h and zip.c 

### ISSUE THREAD

**Issue by UAchar** [kuba--/zip#198]
Some more level 4 warnings appear during compilation:
![image](https://user-images.githubusercontent.com/86720341/125949179-e2f9d425-cb6c-49fc-b8bf-aed503337a62.png)

![image](https://user-images.githubusercontent.com/86720341/125949407-690fed6d-0efe-4566-b0fd-ff018aa935a7.png)

**Comment by kuba--** [comment]
Thanks, 
I addressed the first part of warnings here: https://github.com/kuba--/zip/pull/199

I would not worry much about the second part (zip.c:212, ...). If you know what's going on it's pretty clear.

**Comment by codylico** [comment]
maybe for the assignment in conditional, you can put extra parentheses
around it; that may let the compiler know what you intend (i haven't tested
it though).

**Comment by kuba--** [comment]
@codylico - it's already done in this way:
`for (i = 0; (i < n) && (c = *str++); ++i)`
` if (!(stream = MZ_FOPEN(filename, "rb")))`
`if ((err = zip_entry_openbyindex(zip, i)))`

**Comment by codylico** [comment]
@kuba-- yeah, i agree with you, looks like it is. :thinking: 

only other idea i have then is to put an explicit `!= 0` in the expression. but, depending on the library goals that may be too much effort for one compiler.
