### ISSUE TITLE
Create a subdirectory for "zip_entry_open", "zip_extract" does fail

### ISSUE THREAD

**Issue by alexsilva** [kuba--/zip#2]
zip_entry_open(zip, "subdir/foo-1.txt");

zip_extract(zfilename, "/tmp", on_extract_entry, &arg);

result

-1

**Comment by kuba--** [comment]
Hi Alex, I've fixed it on master, so please take a look if it works for you.

**Comment by alexsilva** [comment]
Working now, thanks.
