### ISSUE TITLE
Strange characters at the bottom of the file

### ISSUE THREAD

**Issue by squirlyfoxy** [kuba--/zip#201]
I am trying to read a json file from an archive and to serialize it via nlohmann's json library but (as you can see in the screenshot), the variable contains at the bottom some strange characters which prevent the library from serializing correctly and leads the program to an exception

![Immagine](https://user-images.githubusercontent.com/48452585/126662027-6dbf39c5-23c0-4f51-8811-01c7a01ee5c9.png)

How I read:

const char* ara::ARAResourceSystem::MapType(ARAResourceType t)
{
    static const char* a[] = {
        "texture",
        "maps",
        "prefabs",
        "misc"
    };

    switch (t) {
    case ARA_RESOURCE_TYPE_MAPS:
        return "maps";
    case ARA_RESOURCE_TYPE_MISC:
        return "misc";
    case ARA_RESOURCE_TYPE_TEXTURE:
        return "textures";
    case ARA_RESOURCE_TYPE_PREFABS:
        return "prefabs";
    default:
        return nullptr;
    }
}

ara::File ara::ARAResourceSystem::LoadFileIntoMemory(const char* f_name, ARAResourceType f_type)
{
    if (!m_can_access) { LOG_F(WARNING, "Resource System not initialized"); } //Not Loaded

    File f = {nullptr, 0};

    //size_t buff_size = 0x0;
    //void* buff = NULL;
    //memset(&buff_size, 0, sizeof(size_t));

    const char* folder = MapType(f_type);

    if (folder == nullptr) {
        LOG_F(ERROR, "Resource type not found");
        return f;
    }
    
    //Find file in vector
    for (int i = 0; i < m_res_vector.size(); i++) {         // TODO: OPTIMIZE THIS SEARCH ALGORITH
        if(strcmp(m_res_vector[i].m_f_name, f_name) == 0) {
            //Load in memory
            std::stringstream ss_1; //Archive path
            std::stringstream ss_2; //Path in archive
            char* a_name = m_res_vector[i].m_archive_name;

            ss_1 << a_name;
            ss_2 << "project_ara\\assets\\" << folder << "\\" << f_name;

            std::string archive_path = ss_1.str();
            std::string in_archive_path = ss_2.str();

            struct zip_t* zip = zip_open(archive_path.c_str(), 0, 'r');
            {
                ssize_t t;
                zip_entry_open(zip, in_archive_path.c_str());
                {
                    t = zip_entry_read(zip, &f.buff, &f.buff_size);
                }
                zip_entry_close(zip);
            }
            zip_close(zip);

            break;
        }
    }

    return f;
}``

thanks in advance and sorry for my english if it is not correct

**Comment by kuba--** [comment]
But how it's related to the zip library?
Who, how put those characters (trash) there?
Do you use returned `f.buff_size`?

**Comment by squirlyfoxy** [comment]
I return a struct witch contains a void* and a size_t

**Comment by kuba--** [comment]
you  can attach the zip file, so I can try to unzip it. My point is that maybe you don't tailor the buffer by size, so the rest of the stuff is just garbage.

**Comment by squirlyfoxy** [comment]
[test_world.zip](https://github.com/kuba--/zip/files/6865473/test_world.zip)

I create the archives after the build by launching a c# program written with the ICSharpCode zip library if it can help

**Comment by kuba--** [comment]
I don't see any garbage in the file after I decompress it, but you can also (temporary) try to copy n bytes (in your case 630) and deserialize it, e.g.:
```c
void *buf = NULL;
size_t bufsize;

	struct zip_t* zip = zip_open("/tmp/maps.zip", 0, 'r');
        {
            zip_entry_open(zip, "project_ara/assets/maps/test_world.world");
            {
                zip_entry_read(zip, &buf, &bufsize);
            }
            zip_entry_close(zip);
        }
        zip_close(zip);

printf("size: %zu\n", bufsize);
char *tmp = (char *)calloc(bufsize+1, sizeof(char));
snprintf(tmp, bufsize, "%s", (char *)buf);
printf("'%s'\n", tmp);

free(tmp);

free(buf);
```

Let me know if you also see he garbage in the new (tmp) string.

**Comment by kuba--** [comment]
btw. your first two lines (before you pass file content to the `json.parse`) just blindly convert `void*` to C++ string.
Maybe try to get/convert  just `bufsize` characters and then pass to `parse`.

**Comment by squirlyfoxy** [comment]
I think it's working... thank you very much

![i think it's working](https://user-images.githubusercontent.com/48452585/126752139-619343de-f0cc-4de7-a1e9-1e25af5557b3.png)
