### ISSUE TITLE
Unsafe `_wfopen` and `_wfreopen` in Visual Studio

### ISSUE THREAD

**Issue by mykhailopylyp** [kuba--/zip#205]
Safe versions of  `_wfopen` and `_wfreopen` should be used in VS 2019.

![image](https://user-images.githubusercontent.com/17161067/131490976-c37acf60-531c-4b5b-8de7-fa91fbe55258.png)

**Comment by kuba--** [comment]
Actually, it was changed back to fix an issue on MinGW (https://github.com/kuba--/zip/issues/164)

**Comment by mykhailopylyp** [comment]
We can probably use `_MSC_VER` to ifdef. Any thoughts?

**Comment by kuba--** [comment]
Yeah, I think I'll try with nested defs (one for mingw and the second for msc).

**Comment by kuba--** [comment]
Here is a fix: https://github.com/kuba--/zip/pull/206
which I hope will work for both MSC and MinGW on windows.
