### ISSUE TITLE
can not zip the opened file on windows

### ISSUE THREAD

**Issue by appledragon** [kuba--/zip#219]
Hello kuba,

greate thanks for your zip module,  easy to use for all platforms, thumbs up!!  yesterday I upgraded zip to 0.22, and found on windows platform, the opening files can not be zipped into the zip file, and I checked the source code , found _wfopen_s return error 32, so I check the 
_wfopen_s api from https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-170, it says
in the remark "Files that are opened by fopen_s and _wfopen_s aren't sharable. " so this make sense. would you like to add a macro
in the cmake to let the user decide to use  _wfopen_s or  _wfopen. because in some cases, we need zip the opening files, such like
logs etc.   thanks a lot!!

**Comment by kuba--** [comment]
I think I can consider wrapping https://github.com/kuba--/zip/blob/72cb23c31122566175e2c599406b266644fb0f99/src/miniz.h#L4836

by some _ifdef_ macro.

**Comment by appledragon** [comment]
> I think I can consider wrapping https://github.com/kuba--/zip/blob/72cb23c31122566175e2c599406b266644fb0f99/src/miniz.h#L4836
> 
> by some _ifdef_ macro.

I create a pr, please help to check it , I am not sure it could be acceptable.

https://github.com/kuba--/zip/pull/220
