### ISSUE TITLE
Is unicode supported?

### ISSUE THREAD

**Issue by RCECoder** [kuba--/zip#226]
Is unicode supported in this library?
Does it work with zipping for eg, Japanese/Chinese file names?
Windows/Visual Studio.

**Comment by kuba--** [comment]
just under the hood `wchar_t *str2wstr(const char *str)` function is used in functions like:
`mz_fopen`, `mz_freopen`, `mz_mkdir`

**Comment by RCECoder** [comment]
Thanks, I tried it and it seems to work fine.
