### ISSUE TITLE
Will it work fine on embedded systems?

### ISSUE THREAD

**Issue by Rajssss** [kuba--/zip#231]
Although this looks like but just wanted to make sure, whether it'll work or not in an embedded environment If I have a working fs (littlefs). Let me know your thoughts.

Edit: After a quick test, I found the linker is throwing ftruncate undefined.
My target environment is an esp32 MCU, using an ESP-IDF-based code.
I am using littlefs port for esp32 which can be found here: https://github.com/joltwallet/esp_littlefs
I also found that littlefs already supports ftruncate, don't know what I am missing now,

**Comment by Rajssss** [comment]
It seems its the limitation of the port I am using (maybe littlefs itself?), though it supports truncate but not ftruncate.

**Comment by kuba--** [comment]
@Rajssss if it's just a matter of adding `ifdef` for `littlefs` or custom implementation for just one `truncate` function, I think it's doable.
Of course, as always - all PRs are welcome.

**Comment by Rajssss** [comment]
> @Rajssss if it's just a matter of adding `ifdef` for `littlefs` or custom implementation for just one `truncate` function, I think it's doable. Of course, as always - all PRs are welcome.

truncate is already implemented on IDF side, but truncate isn't.

https://github.com/espressif/esp-idf/issues/8279

**Comment by Rajssss** [comment]
Thank you for your time and amazing work again @kuba-- I am closing this issue now.
And for my application, I have used miniz directly, but will try to use this one too but later.
