### ISSUE TITLE
ISO C90 forbids mixed declarations and code and some other errors

### ISSUE THREAD

**Issue by tansy** [kuba--/zip#232]
First try:
```
$ cmake -G"Unix Makefiles"
$ make
```
and then whole bunch of errors.

```
zip-0.2.2-1/src/miniz.h:4391:27: error: C++ style comments are not allowed in ISO C90 [-Werror]
           (void)rev_code; // unused
(...)
zip-0.2.2-1/src/zip.c:259:3: error: ISO C90 forbids mixed declarations and code [-Werror=pedantic]
   mz_bool res = (strcmp(name1, nname2) == 0) ? MZ_TRUE : MZ_FALSE;
   ^
                           ^
```

So I removed `-Werror -pedantic` as, obviously, code does not follow pedantically pedantic rules. This way I was able to compile the library with bunch of warnings though. Some of them are pretty interesting and concerning, I would say. More to that later.

Then it come test with this error:
```
test_permissions.c:(.text+0x1e): undefined reference to `clock_gettime'
```

Quick solution to that is to ad `-lrt` to linked libraries:
```
+target_link_libraries(${test_write_out} zip rt)
```
And this is true for all test as they all measure time. I just show one to not flood a post.

One of the things I noticed in those warnings is this warning:
```
zip-0.2.2-1/test/test_entry.c:96:3: warning: this decimal constant is unsigned only in ISO C90
   mu_check(CRC32DATA1 == zip_entry_crc32(zip));
   ^
```
It compares CRCs and if these values are different in signedness this can lead to wrong results.
And there are lot of them.

Another one is:
```
... zip-0.2.2-1/src/miniz.h:4968:9: note: #pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.
 #pragma message(                                                               \
         ^
```
On 32-bit systems there should be set `_FILE_OFFSET_BITS` set to 64 and this would solve the problem. I come up with solution that checks system  than just simply adding this definition as it is (or should be) defined on 64-bit systems:
```
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    # large file support
    add_definitions(-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64)
endif()
```
On 64-bit systems it should return empty string as file functions are 64-bit already.

From my tests, and not only my I guess, there is no need to add `_LARGEFILE_SOURCE` even if `$ getconf LFS_CFLAGS` returns it but I added it 'just in case' as documentation is unclear here and [headers](http://ac-archive.sourceforge.net/largefile/glibc.html) seem to define macro if `_FILE_OFFSET_BITS=64` is set not the other way around.

**Comment by kuba--** [comment]
What compiler and libc do you use? For instance `-lrt` (realtime extensions library) contains old functions for backward compatibility (which now resides in libc), e.g. `clock_gettime` is in `time.h`.

Changing declaration and/or comments style is doable (of course any PR is welcome), but generally the code which you pointed out has not been changed for a while and nobody had came across similar issues (me included). That's why I wonder about os/compiler/libc version.

**Comment by tansy** [comment]
Libc.so.6 says 2.15, slackware.
Gcc 4.7, 4.9, 6.1. Clang 3.8 this one didn't complain about ISO C90, but abut librt yes).
I don't have much problem with that as it afeects tests and these errors only indicate "old fashioned" syntax.

And large file support in 32-bit systems is still open question.

**Comment by kuba--** [comment]
I think there is no problem to add following snippet to cmake file:
```
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    # large file support
    add_definitions(-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64)
endif()
```

**Comment by kuba--** [comment]
@tansy - Does the current state (on master) work for you?
Do you need `target_link_libraries(${test_write_out} zip rt)`?

**Comment by tansy** [comment]
I got what you said about `librt` being in libc now. I can manage without it being "forced" into "main stream".
Out of curiosity, what happens if you have librt functions in libc and still add it to link. Will it link to librt.so or not?
