### ISSUE TITLE
Segfaults when deleting entries for in memory zip

### ISSUE THREAD

**Issue by prot0man** [kuba--/zip#241]
When you instantiate a an in memory zip, add a file, then try to remove it, `zip_entries_delete_mark` segfaults.

Looks like when you're doing https://github.com/kuba--/zip/blob/master/src/zip.c#L752 you don't check for if pState->m_pFile is NULL before seeking. I started to create a PULL request fixing that, but looks like there are a few other issues further down the line after deleting a file for an in memory zip.

**Comment by kuba--** [comment]
@prot0man - 
Could you give some steps to reproduce the issue (deleting entries is pretty fresh-new feature).
Extra checking `pState->m_pFile` is not a big deal, but most likely the problem is somewhere else.

**Comment by kuba--** [comment]
Please reopen the issue, if you can give  some staps to reproduce the issue
