### ISSUE TITLE
Compile error on android

### ISSUE THREAD

**Issue by paroj** [kuba--/zip#243]
- ndk-r21e
- platform-16
```
 /home/runner/work/ogre/ogre/OgreMain/src/zip/zip.c:1382:68: error: use of undeclared identifier 'S_IWRITE'
  zip->entry.external_attr = (modes << 16) | !(file_stat.st_mode & S_IWRITE);
                                                                   ^
/home/runner/work/ogre/ogre/OgreMain/src/zip/zip.c:1718:60: error: use of undeclared identifier 'S_IWRITE'
    ext_attributes = (modes << 16) | !(file_stat.st_mode & S_IWRITE);
```

**Comment by kuba--** [comment]
Can you check if removing `set(CMAKE_C_STANDARD 90)` from `CMakeLists.txt` fixes the issue?

**Comment by paroj** [comment]
this is using ogre cmake, which does not set that flag.

according to this:
https://stackoverflow.com/questions/39855672/tensorflow-how-to-compile-libtensorflow-cc-so-for-android

you should rather be using S_IWUSR

**Comment by kuba--** [comment]
Yeah, on most platforms this is just an alias, but if it fixes the issue, here you go:
https://github.com/kuba--/zip/pull/244
