### ISSUE TITLE
`zip_entry_openbyindex` takes int as index parameter

### ISSUE THREAD

**Issue by evilenzo** [kuba--/zip#247]
Why? Why not size_t? I just tried to do this:
```c++
for (size_t i = 0, n = zip_entries_total(zip); ++i) {
    zip_entry_openbyindex(zip, i);
    // some code
}
```
And got warning that `zip_entry_openbyindex` takes int. As far as I know index can not be negative....

**Comment by kuba--** [comment]
`int` is defined everywhere, but `size_t` can be pretty tricky. 
Anyway, here is PR: https://github.com/kuba--/zip/pull/249
which may work for you - PTAL.
