### ISSUE TITLE
Cannot unzip file on macos 10.14.6

### ISSUE THREAD

**Issue by nosleduc** [kuba--/zip#250]
Hi

I'm testing this library to make zip files that will be read by another application made by someone else.
This application fails to read my zip file. 
The zip file can be read with the integrated reader of Windows and also with 7zip.
The integrated zip utility tool of macos is not able to unzip this file. 
I have an error like "Unable to expand".

When I'm unzipping the file with the library, there is no error.
It seems for me that the problem may come from something about 64 header

**Comment by kuba--** [comment]
So, let me understand the problem - the library, windows zip tool and 7zip don't have any problems to zip/unzip the file. Only macos zip utility is not able to unzip the file.
Don't you think it's the tool's issue?
Do you have more details, like `zipinfo -v` output?
Can you send the _zip_ file?

**Comment by kuba--** [comment]
@nosleduc - Please feel free to re-open the issue, if you have more details to investigate.

**Comment by nosleduc** [comment]
Yes it works with the integrated zip tool of windows and also with 7zip but not with the integrated zip tool of macos.
It reports me an error and it cannot unzip the file
It may be a problem of the integrated tool of macos but it is not really my issue.

My concern is about an another application made by someone else that tells me that my file cannot be read. 
In my application, I can change easily the tool I'm using to make the zip files. If I'm using Quazip instead instead of your library, it works in every cases.

Here are the output of zip info

zipinfo -v hello.zip                        ✔  14:21:05 
Archive:  hello.zip
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                       232 (00000000000000E8h)
  Actual end-cent-dir record offset:           134 (0000000000000086h)
  Expected end-cent-dir record offset:         134 (0000000000000086h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 1 entry.
  The central directory is 55 (0000000000000037h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 79 (000000000000004Fh).


Central directory entry #1:
---------------------------

  Hello

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
  version of encoding software:                   0.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           not encrypted
  extended local header:                          yes
  file last modified on (DOS date/time):          2022 Apr 26 12:32:02
  32-bit CRC value (hex):                         8bd69e52
  compressed size:                                16 bytes
  uncompressed size:                              11 bytes
  length of filename:                             5 characters
  length of extra field:                          4 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  non-MSDOS external file attributes:             81A400 hex
  MS-DOS file attributes (00 hex):                none

  The central-directory extra field contains:
  - A subfield with ID 0x0001 (PKWARE 64-bit sizes) and 0 data bytes.

  There is no file comment.

**Comment by kuba--** [comment]
Hmm, everything looks fine. 
Maybe it's the case related permissions. What operating systems are used? How do you compress the file(s)?
