### ISSUE TITLE
Usage together with minz?

### ISSUE THREAD

**Issue by Jakz** [kuba--/zip#253]
Hi!
I'm trying to integrate this library as a replacement for zlib which I was currently using to also gain support for archives.

I was using zlib to inflate/deflate raw buffers in memory as I need that feature too, I've been able to replace the calls to minz calls.

When adding this library though, it looks like that, since everything is defined in the header, I get duplicate symbols error at linking phase since I'm trying to use minz functions both in my code and in zip.c code.

How am I supposed to have zip.c functions and be able to use minz functions in my own code?

**Comment by kuba--** [comment]
You can try to compile zip library as  shared library (link it dynamically), but compile miniz into your source.
For example:
```
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=true .. 
```

```
// main.c
#include <zip.h>
#include <miniz.h>

struct zip_t* z = zip_open("/tmp/test.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
zip_close(z);

printf("miniz version: %s\n", mz_version());
```

```
gcc -Wall -I ../src -L . -lzip main.c -o main.exe
```

**Comment by kuba--** [comment]
@Jakz - please re-open the issue, if you have any other questions.
