### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by rudolfninja** [kuba--/zip#254]
Hey, is it planned to add unicode support for file names and entry names? I tried to modify your code to make it possible create unicode names for entries and add uncicode files, but failed. It seems that the problem is in unicode entry name, but not the file itself.

**Comment by kuba--** [comment]
Frankly, I don't have any plans to extend API with `wchar_t` etc., but you can take a look into the issues, where we discussed how to solve the problem (mainly on windows):

https://github.com/kuba--/zip/issues/39
https://github.com/kuba--/zip/issues/226
https://github.com/kuba--/zip/issues/26

@rudolfninja - if you have any other questions, please re-open the issue.
