### ISSUE TITLE
something wrong in linux

### ISSUE THREAD

**Issue by muyuanjin999** [kuba--/zip#256]
i try to add 3 files（zip.h zip.c miniz.h) in my project to create zip in centos/ubuntu, and i get this 
![f15e0d41545a9487ffc67e306418005](https://user-images.githubusercontent.com/64581006/167361114-94223b6e-951d-401a-8e20-f6a11851bbc5.png)
Could someboy tell me how to solve it?Or it cound not work just by adding 3 files?

**Comment by kuba--** [comment]
@muyuanjin999 - how do you compile your project?

On Linux, for symlink you need `<unistd.h>`, `S_IF...` are in `<sys/stat.h>`.
Do you have glibc (or any C-standard library headers) installed on your machine?
