### ISSUE TITLE
Suggestion: can we have zip_entry_write write as chunks?

### ISSUE THREAD

**Issue by RCECoder** [kuba--/zip#257]
This is not an issue but a suggestion, can we have the function `zip_entry_write` write as chunks? or just another similar function.
As of right now, it writes the whole zip in memory so it's not ideal for huge files. 
It would be helpful so that the function can continue in writes with buff+bytesWritten,NumOfBytes
Not sure if that's even possible due to the CRC I think?
Example:
```
	
	{

		
		struct zip_t *zip = zip_stream_open(NULL, 0, ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
		{
			zip_entry_open(zip, "foo-1.txt");
			{
				
				int numberOfWrittenBytes = 0;
				const int ChunkSize = 0x1000;
				int WriteSize;
				while (numberOfWrittenBytes < FileSize)
				
				{

					WriteSize = FileSize - numberOfWrittenBytes;
					if (WriteSize > ChunkSize) {
						WriteSize = ChunkSize;

					}

					zip_entry_write(zip, buff+numberOfWrittenBytes , WriteSize);
					numberOfWrittenBytes += ChunkSize;
				}
				
			}
			zip_entry_close(zip);

			/* copy compressed stream into outbuf */
			zip_stream_copy(zip, (void **)&outbuf, &outbufsize);
			
		}
		zip_stream_close(zip);

		free(outbuf);

	}
```

**Comment by kuba--** [comment]
@RCECoder - thanks for the suggestion.
You can always split your file/buffer into chunks and you can merge them as one zip entry, e.g.:
```c
zip_entry_open(zip, "foo-2.txt");
    {
        // merge 3 files into one entry and compress them on-the-fly.
        zip_entry_fwrite(zip, "foo-2.1.txt");
        zip_entry_fwrite(zip, "foo-2.2.txt");
        zip_entry_fwrite(zip, "foo-2.3.txt");
    }
    zip_entry_close(zip);
```

you can also use `_write` instead of `_fwrite`.

**Comment by RCECoder** [comment]
Yes, that's exactly what I did in my example by issuing `zip_entry_write` calls in a loop until that large (single file) is zipped. After the loop is done, calling `zip_stream_copy` would actually result in the last chunk zipped only. I think If we have 1 big file, there isn't a way to compress it in memory as chunks as I have seen the CRC check needs the whole file buffer in memory for its calculation.
