### ISSUE TITLE
unicode file names in zip content?

### ISSUE THREAD

**Issue by ZSaberLv0** [kuba--/zip#26]
does it support unicode files names in zip content?

try to pass some UTF-8 chars as file name, but got wrong file names when opened by other zip tools, won't happen if all file names are ASCII chars

**Comment by kuba--** [comment]
@ZSaberLv0 - yes and no. Internally we use standard `char *` type for names (no wchar_t *, etc).
Moreover, in your case other tools may support utf-8 in different ways on different platforms (what happens very often). So if you use the _zip_ library on _unix_ to compress/decompress files it looks pretty ok, e.g.:
```c
struct zip_t *zip = zip_open("/tmp/test.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
zip_entry_open(zip, "test/厦门市.txt");
zip_entry_close(zip);
zip_close(zip);

zip_extract("/tmp/test.zip", "/tmp/", NULL, NULL);
```

you can see it has extrcted the archive correctly, even if _zipinfo_ prints some trash.

**Comment by ZSaberLv0** [comment]
@kuba-- sorry for not fully testing, when compiled under Mac, works fine for zip_extract and Mac's default unzip, but doesn't work for 7-zip under Windows

so, is there anyway to support all zip tools?

**Comment by kuba--** [comment]
If everybody follow the same standard then maybe yes, but there is another problem encoding on each operating system. Quoting [this blog](https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/):

> The Zip spec does not seem to know that there are normalization models for UTF-8, when there are actually 4 (or more, because there is some non-standard ones too!). The Zip file gives no guidance as to how file names inside zip files are to be normalized.
> 
> Consider, when a zip file is created on Linux, it just writes the bytes for the file name in the encoding of the underlying file system. So, if the file system is in ISO-8859-1, the bytes are written in ISO-8859-1. This may seem ok, but when you decompress the zip file on Windows, which runs on encoding Windows-1252, the file names get all mangled. If the underlying encoding of the file system on Linux is something else, you won’t be able to share files with other systems at all. So in this case, it is not Window’s fault.

**Comment by ZSaberLv0** [comment]
yeah, after some test, i think there's no platform independent solutions, thanks for the description

**Comment by UAchar** [comment]
miniz supports UTF-8 for zip filenames since version 2.0.3.  
when I pass this bit flag while creating the header: "mz_zip_writer_add_to_central_dir" in zip_entry_close(),  the zip internal files will show correct names in other zip tools too.
Is it possible to push this change?

**Comment by kuba--** [comment]
@UAchar - sure.
Take a look if this _silly_ change is good enough and works for you:
https://github.com/kuba--/zip/pull/214
