### ISSUE TITLE
About the zip library cross-platform issue

### ISSUE THREAD

**Issue by Sugar0612** [kuba--/zip#277]
Can the zip library be used normally in the android environment like in the windows platform?

**Comment by Sugar0612** [comment]
hi guys, I use the zip library here and compile it into a so file and run it on the android platform (the windows platform is no problem), but I found that the zip returned by zip_open(...) is null, I don't know why, do I need to do something in advance on the android platform, or how should I do it?

**Comment by kuba--** [comment]
You do not have to do anything special on Android (it's just a Linux kernel OS).
Without any snippet and/or intention what you try to do (zip/unzip, etc.) it's hard to address your issue.

**Comment by Sugar0612** [comment]
> You do not have to do anything special on Android (it's just a Linux kernel OS). Without any snippet and/or intention what you try to do (zip/unzip, etc.) it's hard to address your issue.

First of all, thank you for your answer, that is, the .apk I generated (the location of this .apk is in '/storage/emulated/0/.apk') file contains such a piece of code 
`struct` zip_t *zip=zip_open("filename", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
     if (!zip) {
         std::cerr << "zip is Error!" << std::endl;
         ANDROID_LOG(oss_log, Error, "zip is Error!");
     }
     else {
         std::cerr << "zip create Success!" << std::endl;
         ANDROID_LOG(oss_log, Error, "zip create Success!");
     }`
I found that the zip object returned NULL, and I don't know why it is like this

**Comment by Sugar0612** [comment]
> You do not have to do anything special on Android (it's just a Linux kernel OS). Without any snippet and/or intention what you try to do (zip/unzip, etc.) it's hard to address your issue.

Problem solved, thank you~
