### ISSUE TITLE
Created a zip in OSX platform but when java.util.zip is used for unzipping it doesn't work

### ISSUE THREAD

**Issue by ArunBViru** [kuba--/zip#279]
Hello,
I created a zip using the awesome kuba-- zip library. Unzipping works fine on Mac OS finder. 
But when the zip file is inputted to java program and unzipped using java.util.zip, it crashes as below. BTW java program is executed on Android platform.

Executing task 'MyClass.main()'...

Executing tasks: [MyClass.main()] in project /Users/arun.bv/AndroidStudioProjects/MyApplication

> Task :lib:compileJava
> Task :lib:processResources NO-SOURCE
> Task :lib:classes

> Task :lib:MyClass.main()
Unzipping to /Users/arun.bv/Pictures/LUTs/CheckZip/1/output/BCSMaxLUT.mat

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 544ms
2 actionable tasks: 2 executed
java.util.zip.ZipException: invalid entry size (expected 0 but got 9696 bytes)
	at java.base/java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:400)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:199)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.example.lib.MyClass.unzip(MyClass.java:39)
	at com.example.lib.MyClass.main(MyClass.java:16)
Task execution finished 'MyClass.main()'.

**Comment by kuba--** [comment]
It's hard to say, why your java app cannot unzip archive. Does it work on non-android platform? How about permissions? Maybe because of `ZIP64` is not supported by `java.util.Zip`.

**Comment by ArunBViru** [comment]
Hello,
Yes. I works well on non-android platform. Only on Android app, it doesn't work. Yes even i think ZIP64 support unavailability. 
Anyway we can make zip file generated using Kuba--zip to work on any platforms?

**Comment by kuba--** [comment]
As far as I know the library works fine on OSX, Linux, Windows (MSVC and MinGW) and on Android (which is actually linux kernel os.). But we cannot fix java on Android. 
Maybe you need to upgrade your JDK on Android or try some older versions of the zip library (e.g. before we upgraded to 0.2.0, for instance: https://github.com/kuba--/zip/releases/tag/v0.1.32)

**Comment by ArunBViru** [comment]
Hello Kuba,
Thanks for the update on this issue. I will try out the options suggested by You. 
BTW, the library is pretty neat and easy to integrate to the project as well. Kudos!

**Comment by kuba--** [comment]
Closing so far.
