### ISSUE TITLE
Update files in zip

### ISSUE THREAD

**Issue by HappyLongShort** [kuba--/zip#284]
When opening a zip file like below and trying to replace an entry inside ,it creates 2 files with the same name.
 struct zip_t* zip = zip_open("foo.zip", 0, 'a');
Is there any way to replace or update the file?

**Comment by kuba--** [comment]
Hey,  there is such a thing like replace/update in place. The `a` mode stands for `append`, so you can just append new entries to the existing archive.
If you want to replace existing entry, you may try to delete the entry first, and then create a new one with the same name.
