### ISSUE TITLE
Extract without a path

### ISSUE THREAD

**Issue by gvanem** [kuba--/zip#287]
I just found this nice library and I'm trying to add it to my project.
I need to handle a .zip with a single file:
`media/data/samples/metadata/aircraftDatabase.csv`

Currently I spawn an external unzip program like this:
```
unzip -p c:\\temp\\aircraft-database-temp.zip > c:\\temp\\aircraft-database-temp.csv
```

Option `-p` writes to `stdout`.

So now calling:
```
zip_extract (\"c:\\temp\\aircraft-database-temp.zip\", \"c:\\temp\", NULL, NULL);
```

I end up with `c:\temp\media\data\samples\metadata\aircraftDatabase.csv`.
But I want `c:\temp\aircraftDatabase.csv`.

I could probably call `CopyFile()` in a callback, but I'm wondering if there's a special flag for this?

**Comment by kuba--** [comment]
It makes a path because the entry name is `\media\data\samples\metadata\aircraftDatabase.csv` (take z look `zipinfo -v`).

What I would suggest is:
```
zip_open(ZIPNAME, 0, 'r');

zip_entry_openbyindex(zip, 0);
zip_entry_fread(zip, "my name"); // original name you can get by calling zip_entry_name
zip_entry_close(zip);

zip_close(zip);
```

**Comment by gvanem** [comment]
Okay, thanks. I'll try it. Or go back to the original miniz which has a flag for this.
