### ISSUE TITLE
How to change to zip and not use zip64?

### ISSUE THREAD

**Issue by veteri** [kuba--/zip#289]
It seems that zip64 is just forced in the code.

Example:
Hardcoded usage of 
`MZ_ZIP_FLAG_WRITE_ZIP64`
and size of zip64 everywhere.

Any easy way to change it to write zip instead?
Removing the flag still writes zip64.

**Comment by kuba--** [comment]
You can try to use older version of the library, e.g. v.0.2.1 where we do not use miniz v2 API

**Comment by kuba--** [comment]
Thanks, would be great if you can send PR - always welcome
