### ISSUE TITLE
Open zip file using file descriptor or stream

### ISSUE THREAD

**Issue by bruenor41** [kuba--/zip#291]
Hi, 

Android restrictions on public storage block direct file paths. But I can get file descriptor for archive from system. 

Please is possible to open and extract zip by passing file descriptor of existing zip file?

And the same for zipping. I can get file descriptor for newly created binary file with zero length which can be passed to zip function as a base for zip file.

Just now I create zip in private storage location, this location is not restricted and file paths works here. But then I must copy resulted file out. This is double work and operation takes more time.

**Comment by kuba--** [comment]
It will require many small changes in `minizip`, so if your files are not _super big_ you can read them into memory and use `zip_stream_...` API

**Comment by bruenor41** [comment]
Thank you for fast response. Before zip process I do save state of various
components, i save variables and arrays using stream to around 20 small
files (from 1 to 20MB). Resulted files are zipped together. Maybe I can
write them into memory stream, instead file stream first.

**Comment by kuba--** [comment]
Yeah, definitivelly ( it does not sound like a big archive). You can do sth. like:
 https://github.com/kuba--/zip/blob/master/test/test_entry.c#L176

**Comment by bruenor41** [comment]
Thanks for code. If I understand it well, it creates memory stream and save
there one file test1-txt. Then you copy buffer. And you extract it. But at
the end after zip I need save the memory to providing FILE* stream.

**Comment by kuba--** [comment]
I assume you already have a file descriptor where you want to save the _zip stream_. 
Then:

```c
        // create zip stream in memory
	struct zip_t *zip = zip_stream_open(NULL, 0, ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');

        // write some data
	zip_entry_open(zip, "entry1.txt");
	const char *txt = "This is content for entry1.txt\0";
	zip_entry_write(zip, txt, strlen(txt));
	zip_entry_close(zip);

        // get zip stream into the buffer
	char *buf = NULL;
	size_t bufsize = 0;
	zip_stream_copy(zip, (void **)&buf, &bufsize);

	zip_stream_close(zip);

        // we should already have a file descriptor
	int fd = open("/tmp/file.zip", O_CREAT|O_WRONLY|O_TRUNC, S_IRUSR | S_IWUSR);
        // write zip stream to your file descriptor
	write(fd, buf, bufsize);
	close(fd);

        // remember to free memory allocated for the buffer!
	free(buf);
```

Keep in mind - there is no error checking in above example.

Good luck!

**Comment by bruenor41** [comment]
Perfect, that's exactly what I need:)

Many thanks for your help and awesome library.
