### ISSUE TITLE
Bug when delete a file from a big size zip archive

### ISSUE THREAD

**Issue by BassamNa** [kuba--/zip#297]
When I have tried to delete a file from a big size zip archive (I have one of more than 6GB), the delete operation "zip_entries_delete" failed because the zip_entry_mark function marks many files have archive index as less than the archive index of the deleted file as an MZ_MOVE, while it should be marked as MZ_KEEP and only the files that have an archive index greater than the deleted file archive index will be marked as MZ_MOVE. 
The error exists at: 
https://github.com/kuba--/zip/blob/master/src/zip.c#L444
I have fixed this issue by assign ~0ULL value to the d_pos rather than ~0UL:
`mz_uint64 d_pos = ~0ULL; `
Could you please update the zip_entry_mark  code?

**Comment by CPP-Team-Ltd** [comment]
> `mz_uint64 d_pos = ~0ULL;` 

Interesting fix!

**Comment by BassamNa** [comment]
> What compiler did you use? Because on clang following code gives the same values.
Thanks, I think this issue is machine dependent,  so on your machine the default size of long is 64 bit.
On Linux and mac os the default size of the long is 64 bit.
I'm working on Windows os and use MS visual studio compiler.
> Anyway, I've fixed it by setting `UINT64_MAX`. Should be already merged into master. PTAL
Thanks.
