### ISSUE TITLE
zip_create Why does create not support directory creation！

### ISSUE THREAD

**Issue by fengshangren** [kuba--/zip#301]
zip_create Why does create not support directory creation

**Comment by kuba--** [comment]
For zip there is no such a thing as directory, because you compress the content. All naming is just a convention saved as metadata.
So, if you want to create a directory by unzipping an archive, this is how you can create it:
```c
	struct zip_t *zip = zip_open("/tmp/foo.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
        zip_entry_open(zip, "mydir/");
	zip_entry_close(zip);
	zip_close(zip);

```

**Comment by fengshangren** [comment]
> 对于zip，没有目录这样的东西，因为你压缩了内容。所有的名字只保存为元数据的约定。 所以，如果你想通过压缩文件来创造一一个目录，你可以这样创建它：
> 
> ```c
> 	struct zip_t *zip = zip_open("/tmp/foo.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
>         zip_entry_open(zip, "mydir/");
> 	zip_entry_close(zip);
> 	zip_close(zip);
> ```

Thank you for your answer. Let me ask you another question. If I need multiple threads to compress or decompress files, how do I do it

**Comment by kuba--** [comment]
> Thank you for your answer. Let me ask you another question. If I need multiple threads to compress or decompress files, how do I do it

The library is not thread safe, so you have to handle concurrency by yourself. But frankly speaking it does not really make sense reading/writing on one thread and modifying zip entry offset on another.

I'm not sure what's your use case, but on most OSs your concurrent writes will be blocked by the kernel, so at the end it will work like a sequential writes.
