### ISSUE TITLE
zip_close error when opening zip archive in read mode

### ISSUE THREAD

**Issue by abrasat** [kuba--/zip#305]
Is the call of zip_close() necessary when reading an *.zip archive ( **zip_open(zipFilePath, 0, 'r')** ) , as in the code samples, for example here:
```
void *buf = NULL;
size_t bufsize;
struct zip_t *zip = zip_open("foo.zip", 0, 'r');
{
    zip_entry_open(zip, "foo-1.txt");
    {
        zip_entry_read(zip, &buf, &bufsize);
    }
    zip_entry_close(zip);
}
zip_close(zip);
free(buf);
```
Because zip_close() calls mz_zip_writer_finalize_archive()
```
void zip_close(struct zip_t *zip) {
  if (zip) {
    // Always finalize, even if adding failed for some reason, so we have a
    // valid central directory.
    mz_zip_writer_finalize_archive(&(zip->archive));
...
```
which sets an error if the m_zip_mode is not MZ_ZIP_MODE_WRITING
```
mz_bool mz_zip_writer_finalize_archive(mz_zip_archive *pZip) {
  mz_zip_internal_state *pState;
  mz_uint64 central_dir_ofs, central_dir_size;
  mz_uint8 hdr[256];

  if ((!pZip) || (!pZip->m_pState) || (pZip->m_zip_mode != MZ_ZIP_MODE_WRITING))
    return mz_zip_set_error(pZip, MZ_ZIP_INVALID_PARAMETER);
```

**Comment by kuba--** [comment]
Yep `zip_close` is needed also for reading (to end reader and deallocate memory), but you are right - we should add `if` to check zip_mode and not calling `writer` function when archive is opened for reading.

**Comment by abrasat** [comment]
Ok, thanks. You mean something like this:
```
void zip_close(struct zip_t *zip) {
  if (zip) {
    mz_zip_archive *pZip = &(zip->archive);
    // Always finalize, even if adding failed for some reason, so we have a
    // valid central directory.
    if (pZip->m_zip_mode == MZ_ZIP_MODE_WRITING) {
        mz_zip_writer_finalize_archive(pZip);
        zip_archive_truncate(pZip);
        mz_zip_writer_end(pZip);
    }
    mz_zip_reader_end(pZip);

    CLEANUP(zip);
  }
```

**Comment by kuba--** [comment]
> Ok, thanks. You mean something like this:
> 
> ```
> void zip_close(struct zip_t *zip) {
>   if (zip) {
>     mz_zip_archive *pZip = &(zip->archive);
>     // Always finalize, even if adding failed for some reason, so we have a
>     // valid central directory.
>     if (pZip->m_zip_mode == MZ_ZIP_MODE_WRITING) {
>         mz_zip_writer_finalize_archive(pZip);
>         zip_archive_truncate(pZip);
>         mz_zip_writer_end(pZip);
>     }
>     mz_zip_reader_end(pZip);
> 
>     CLEANUP(zip);
>   }
> }
> ```

Yeah, I think something like this makes sense, the one details I would add:
```c
// ...
if (pZip->m_zip_mode == MZ_ZIP_MODE_WRITING) {
    mz_zip_writer_finalize_archive(pZip);
}

if (pZip->m_zip_mode == MZ_ZIP_MODE_WRITING || pZip->m_zip_mode == MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED) {
        zip_archive_truncate(pZip);
        mz_zip_writer_end(pZip);
}

```

**Comment by abrasat** [comment]
Ok, thx. Should mz_zip_reader_end() be called also when MZ_ZIP_MODE_WRITING ?

**Comment by kuba--** [comment]
LGTM, `mz_zip_reader_end ` is just for `MZ_ZIP_MODE_READING`.
Thanks, I'm waiting for PR ;)
