### ISSUE TITLE
64-bit Linux compatibility

### ISSUE THREAD

**Issue by abrasat** [kuba--/zip#308]
Can the zip library be used also on 64-bit Linux applications?
On 64-bit Linux systems the "unsigned long" datatype has 8-bytes (but on 64-bit Windows only 4-bytes !) (see [here](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=platforms-standard-data-types-aix-linux-windows) )
From miniz.h:
```
...
/* For more compatibility with zlib, miniz.c uses unsigned long for some
 * parameters/struct members. Beware: mz_ulong can be either 32 or 64-bits! */
typedef unsigned long mz_ulong;
...
```
Maybe "unsigned long" should be replaced with "uint32_t" (defined in stdint.h)

**Comment by abrasat** [comment]
Ok, thanks. You mean it should not be a problem to zip a file on Windows and then unzip it on Linux 64-bit?

**Comment by kuba--** [comment]
I believe so.
