### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by thechampagne** [kuba--/zip#314]
I wrote a binding and would like to add it. It would be benefit if there is a list for that or just add binding link above example of the language. Also I consider to write binding for other languages I know.

**Comment by kuba--** [comment]
Do you want to put _some_ language binding in this repo?

**Comment by thechampagne** [comment]
just links

**Comment by kuba--** [comment]
> just links

I think you can add links to the `Bindings` section in `README`

**Comment by thechampagne** [comment]
Could you give an example of how it should look in readme ?

**Comment by kuba--** [comment]
I propose to add `Third party bindings` section at the bottom of  README, where you can put bullet list of links

**Comment by thechampagne** [comment]
How about this:

Language    | Project
----------  | -------
lang-name         | [binding-name](https://github.com/kuba--/zip)
