### ISSUE TITLE
redefinition of 's_tdefl_num_probes' when `miniz.h` included in cpp

### ISSUE THREAD

**Issue by ZSaberLv0** [kuba--/zip#324]
https://github.com/kuba--/zip/blob/master/src/miniz.h#L3113
and
https://github.com/kuba--/zip/blob/master/src/miniz.h#L3995

**Comment by kuba--** [comment]
Thanks, it should be already fixed.
I've applied the fix from https://github.com/richgel999/miniz/commit/b0af33a61b93eec61242b45422529dd466147e9e
