### ISSUE TITLE
Find offset of a file in a zip file?

### ISSUE THREAD

**Issue by IvesAwadi** [kuba--/zip#325]
Would it be possible to get the file offset within a zip file?

Thank you.

**Comment by kuba--** [comment]
Do you mean - zip entry offset (e.g. for a given/opened name)?
What's exactly your use case?

**Comment by IvesAwadi** [comment]
Yes, my use case is reading the /proc/pid/maps directory to find where a shared object with a given name is mapped at in a process virtual space.

Here's a link for reference
[Stackoverflow](https://stackoverflow.com/questions/1401359/understanding-linux-proc-pid-maps-or-proc-self-maps#:~:text=offset%20%2D%20If%20the%20region%20was%20mapped%20from%20a%20file%20(using%20mmap)%2C%20this%20is%20the%20offset%20in%20the%20file%20where%20the%20mapping%20begins.%20If%20the%20memory%20was%20not%20mapped%20from%20a%20file%2C%20it%27s%20just%200.)

**Comment by kuba--** [comment]
Ok, thanks.
I'll add to the feature list.

**Comment by kuba--** [comment]
PR: https://github.com/kuba--/zip/pull/326

**Comment by IvesAwadi** [comment]
Thank you so much, will close the issue now.

**Comment by kuba--** [comment]
> Thank you so much, will close the issue now.

Check the PR if it works for you. Also look at the new test which I've added
