### ISSUE TITLE
PVS-Studio analysis results

### ISSUE THREAD

**Issue by pavel-pimenov** [kuba--/zip#33]
Report:
http://www.fly-server.ru/pvs-studio/zip/

**Comment by kuba--** [comment]
The goal is to fix at least _General Analysis_ potential issue.

**Comment by kuba--** [comment]
https://github.com/kuba--/zip/pull/34

**Comment by kuba--** [comment]
No zip64 support yet

**Comment by kuba--** [comment]
@pavel-pimenov - thanks, couple things were fixed. You can re-run  pvs again. 
Right now I'm closing this issue (added clang's analyzer to a build), but I'll keep the link as a reference. So far no zip64 support.

**Comment by pavel-pimenov** [comment]
@kuba-- 
Update report http://oracle.fly-server.ru/pvs-studio/zip/

**Comment by kuba--** [comment]
thanks
