### ISSUE TITLE
Reading a portion of the file

### ISSUE THREAD

**Issue by KreshMetal** [kuba--/zip#334]
Hello! I'm a very inexperienced C++ programmer, but it happened that I had to work with your library. Is it possible to use it to read not the entire file, but a certain number of its first bytes? Sorry if the question is silly, but I honestly tried to figure it out.

**Comment by kuba--** [comment]
> Hello! I'm a very inexperienced C++ programmer, but it happened that I had to work with your library.
I hope nobody forced you to use this library ;-)

> Is it possible to use it to read not the entire file, but a certain number of its first bytes? Sorry if the question is silly, but I honestly tried to figure it out.

You need to give more context about your use case. Do you want to compress/decompress? You want to read chunk of what - zipped archive, entry, ...?

**Comment by KreshMetal** [comment]
I have file inside archive (like 9mb), and on my computer it took 100ms to read that file with zip_entry_read function. But i need only certain bytes of that file, so reading it full seems not efficient. That's why I ask you, if you can make function, that decompresses and stores in memory only first block or first N blocks of entry. Thanks.

**Comment by kuba--** [comment]
In terms of performance, there is no function to read decompress entries for given offsets.
You can use directly `miniz`, but still it will require a little bit hacks, because under the hood the library checks if given buffer is big enough.

**Comment by KreshMetal** [comment]
Ok, thanks. I'll see what i can do

**Comment by codylico** [comment]
_outsider comment; feel free to ignore_

Would `zip_entry_extract` not work?

**Comment by kuba--** [comment]
> _outsider comment; feel free to ignore_
> 
> Would `zip_entry_extract` not work?

It works, but in terms of performance it does not give you anything, because you still need to allocate memory and read the whole entry.
