### ISSUE TITLE
Flagged as Malicious in Crowdstrike

### ISSUE THREAD

**Issue by konsumer** [kuba--/zip#348]
This may be a non-issue, and I thoroughly looked at source here, and it seems totally fine, but I was testing out a very simple C program on my work laptop, and it triggered a security error. Someone might want to reach out to the Crowdstrike people and figure out why it flags a false-positive.

![image](https://github.com/kuba--/zip/assets/83857/63bdad9d-d74a-40c8-95b9-ab7445c5e68a)

It flagged this hash: `0af566124b346b22365ae668dc603a33ace5ac21b5bf32769c7e6abef22e6087` which I can't seem to find in a web-search.

The program I tested with is this:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "zip.h"

// this represents all shared things for a cart
typedef struct {
  struct zip_t *zip;
} Null0Cart;

// read a file from zip filesystem, as bytes
uint8_t* null0_file_read(Null0Cart cart, char* filename, size_t* bufsize) {
  void *buf = NULL;
  zip_entry_open(cart.zip, filename);
  zip_entry_read(cart.zip, &buf, bufsize);
  zip_entry_close(cart.zip);
  return (uint8_t*)buf;
}

// call when loading the cart to set resources up
Null0Cart null0_cart_load(char* filename) {
  Null0Cart cart;
  cart.zip = zip_open(filename, 0, 'r');
  return cart;
}

// call when unloading the cart to clean up
void null0_cart_unload(Null0Cart cart) {
  zip_close(cart.zip);
}

int main(int argc, char *argv[]) {
  if (argc != 2) {
    fprintf(stderr, "Usage: null0 <CART>\n");
    return 1;
  }
  
  Null0Cart cart = null0_cart_load(argv[1]);
  
  size_t bufsize;
  uint8_t* wasmBytes = null0_file_read(cart, "main.wasm", &bufsize);

  // TODO: do stuff with wasm here

  free(wasmBytes);

  null0_cart_unload(cart);
  return 0;
}
```

Pretty much just "load a zip and extract a file to memory."

My guess is some malware used this lib to extract a payload, but everyone who uses it should not get flagged...

**Comment by kuba--** [comment]
Have you tried with different file?
Maybe it's about reading this particular file, idk?

**Comment by kuba--** [comment]
@konsumer - hey, did you check this file?
Do you have more details? Otherwise I'm going to close the issue.

**Comment by konsumer** [comment]
I can prep the security team on Monday for getting flagged, and do some more testing. It seemed to happen with any zip, when I was testing, before.

**Comment by konsumer** [comment]
I made a simple reproduction [here](https://github.com/konsumer/test-zip-crowdstrike) doesn't seem to matter what is in the zip (I am testing with main.c & makefile, extracting main.c.) Our security-team will try to collect more info.

**Comment by kuba--** [comment]
Looks like false alert, just based on some heuristics like writing to temp dir, rarly running binary, etc.

**Comment by kuba--** [comment]
IMO we can close the issue, because there is nothing to fix in the library.

**Comment by konsumer** [comment]
> Looks like false alert, just based on some heuristics like writing to temp dir, rarly running binary, etc.

yeh, and I am not writing to temp, or running anything from the zip.

> IMO we can close the issue, because there is nothing to fix in the library.

Agreed. seems like a very dumb false-alarm.
