### ISSUE TITLE
Possible license concerns re: miniz

### ISSUE THREAD

**Issue by toasterone** [kuba--/zip#354]
This project came to my attention when a contributor submitted a pull request to a repository I help maintain introducing it as a dependency, so I did my due diligence and wanted to check its licensing situation. I found something with an uncertain answer.

[richgel999/miniz](https://github.com/richgel999/miniz) is MIT-licensed in its source repository, but the modified distribution of `src/miniz.h` is not accompanied by the license-required notice, and appears to be superseded by the Unlicense notice (which has some issues of its own which prevent us using it anyways).

Can you confirm that this project is within the constraints of the source license attached to `miniz`?

**Comment by kuba--** [comment]
`miniz` originally was released under [unlicense.org](http://unlicense.org/) - see https://code.google.com/archive/p/miniz/


I'm not sure when they changed the license, but I'm OK to change it to MIT, just for consistency.
