### ISSUE TITLE
OSS-Fuzz Integration Inquiry

### ISSUE THREAD

**Issue by capuanob** [kuba--/zip#355]
Hello!

I have integrated a few open-sourced projects into OSS-Fuzz, a program sponsored by Google to provide continuous fuzz-testing of impactful open-sourced projects, and am wondering if zip's maintainers would approve me undertaking the work to develop a harness to fuzz-test this library and integrate it into OSS-Fuzz.

If you would like more details on what OSS-Fuzz is and what this work would entail, more details can be found [here](https://google.github.io/oss-fuzz/).

Thank you for your consideration and I look forward to working with you all!

**Comment by kuba--** [comment]
@capuanob - sounds good to me.
Thanks!

**Comment by capuanob** [comment]
@kuba-- Forgot to ask in my initial request, the OSS-Fuzz submission process requires a primary contact to be listed (an email). The primary contact will receive access to ClusterFuzz to view crash reports. Do you have an email you would like to share or would you like me to list myself as the contact?

**Comment by kuba--** [comment]
> @kuba-- Forgot to ask in my initial request, the OSS-Fuzz submission process requires a primary contact to be listed (an email). The primary contact will receive access to ClusterFuzz to view crash reports. Do you have an email you would like to share or would you like me to list myself as the contact?

Frankly speaking, I do not want to make my email public. So, if you can refer my github name `@kuba--`, but keep yourself as contact for ClusterFuzz, that would be great.

Thanks,
