### ISSUE TITLE
zip_entry_fwrite() replace line break from CRLF to LF

### ISSUE THREAD

**Issue by iiiypuk** [kuba--/zip#4]
Subj
``` c
zip_entry_open(zip, "readme.txt");
{
    zip_entry_fwrite(zip, "readme.txt");
}
zip_entry_close(zip);
```
Compiler MSVS 2010

**Comment by kuba--** [comment]
Can you give more details about this issue

**Comment by iiiypuk** [comment]
Sorry. I found the problem.
This is bug `7-Zip File Manager`.
`unzip` and `7z` cli tools unpack right.
