### ISSUE TITLE
Preserve File Permissions

### ISSUE THREAD

**Issue by kappaOne** [kuba--/zip#44]
The ZIP file format stores the file permissions for each of its entries as set on platforms such as linux and mac (i.e. whether a file is executable, etc). However when extracting files with this library it appears that the permissions are not set correctly on the extracted files. So if you zip up an executable file it will not be executable when extracted with this library however if the same zip is extracted by another zip program the files are executable when extracted.

Does this library support this feature or is it possible to add this?

**Comment by kuba--** [comment]
@kappaOne - thanks, I'll take a look and hopefully fix it soon.

**Comment by kuba--** [comment]
@kappaOne - yup, files attributes support should be done as a `external_attr` convention. However _miniz_ doesn't set any attributes (external and internal, except `0x10` for dirs.). If you try any _zipinfo_ tool you can notice sth. like this:
```
Central directory entry #3:
---------------------------

  test/booo.exe

  offset of local header from start of archive:   138
                                                  (000000000000008Ah) bytes
  file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
  version of encoding software:                   0.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2018 Aug 1 08:56:24
  32-bit CRC value (hex):                         00000000
  compressed size:                                2 bytes
  uncompressed size:                              0 bytes
  length of filename:                             13 characters
  length of extra field:                          0 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  non-MSDOS external file attributes:             000000 hex
  MS-DOS file attributes (00 hex):                none
```

I don't know which third-party tools diid you use to extract files, but regular `unzip` doesn't set up any file attributes, so whatever I compress with _zip library_ after unzip has default `644`.
And your _fix_ didn't set anything because `file_stat.m_external_attr` is always 0, so it even cleared all attributes:
```
----------  1 kuba  wheel     0B Aug  1 08:56 booo.exe
----------  1 kuba  wheel    19B Aug  1 08:56 test-1.txt
----------  1 kuba  wheel    19B Aug  1 08:56 test-2.txt
```

**Comment by kuba--** [comment]
@kappaOne - I tested on osx (so no windows, so far) and your fix clears all attributes (as I mentioned above) because for this library external attribute is always 0 for files.
Your fix may work if you compress a file with other tool.

**Comment by kappaOne** [comment]
Ah right, your compressing files using the library first. I've only used it to decompress files using the zip_extract() function. An example file I was using was the Zulu VM found [here](https://cdn.azul.com/zulu/bin/zulu8.30.0.1-jdk8.0.172-macosx_x64.zip). You will note the bin folder therein contains executable files, which when extracted without the above fix are not extracted as executable but are executable when extracting with other zip libraries.

For the files to contain the external attribute when compressing with this library we'll need another fix (the reverse of the above fix), which would read the file permissions and put them into external attribute when compressing.

**Comment by kuba--** [comment]
@kappaOne - I've merged some solution into the master (extracting/chmod in pure C makes sense on UNIX-like systems), so please take a look if it works for you.
If not, please ope this issue or create a new one.

**Comment by kappaOne** [comment]
@kuba-- just tested your fix, works brilliantly for me.

thx for the fix, much appreciated.
