### ISSUE TITLE
Issue generating zip windows MSYS

### ISSUE THREAD

**Issue by hgardneriv** [kuba--/zip#46]
I'm having trouble with a simple example under Windows using MSYS2 where the same example works fine under cygwin and Mac. Here's the code:

#include <iostream>
#include "zip.h"

using namespace std;

int main (int argc, char **argv)
{
    cout << "Generating zip..." << endl;

    struct zip_t *zip = zip_open("foo.zip", ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
    {
        zip_entry_open(zip, "bufWriteEntry");
        {
            const char *buf = "Some data here...";
            zip_entry_write(zip, buf, strlen(buf));
        }
        zip_entry_close(zip);

        zip_entry_open(zip, "fwriteEntry");
        {
            zip_entry_fwrite(zip, "one.txt");
        }
        zip_entry_close(zip);
    }
    zip_close(zip);

    cout << "Done!" << endl;
}

--------------------

After running the test above, the resulting zip file foo.zip is empty:

$ ls -l foo.zip
-rwxr-x---+ 1 Administrator None 65 Aug  1 15:05 foo.zip

$ unzip -l foo.zip
Archive:  foo.zip
warning [foo.zip]:  zipfile is empty

I'm building the library and test apps in MSYS2 MinGW 64 shell as follows:

$ mkdir build
$ cd build
$ cmake -G "MSYS Makefiles" -DBUILD_SHARED_LIBS=true ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/code/zip/build

$ make
Scanning dependencies of target zip
[ 20%] Building C object CMakeFiles/zip.dir/src/zip.c.obj
[ 40%] Linking C shared library libzip.dll
[ 40%] Built target zip
Scanning dependencies of target test.exe
[ 60%] Building C object test/CMakeFiles/test.exe.dir/test.c.obj
[ 80%] Building C object test/CMakeFiles/test.exe.dir/__/src/zip.c.obj
[100%] Linking C executable test.exe.exe
[100%] Built target test.exe

# To build test code above
$ cd ..
$ g++ -D_WIN32 -static-libgcc -static-libstdc++ -std=c++11 -Isrc -static msys-test.cpp build/libzip.dll.a

Any suggestions?

**Comment by kuba--** [comment]
@hgardneriv - does `make test` work for you?

**Comment by kuba--** [comment]
Could you try to add in `zip.c`:
`|| defined(__MINGW64__)` everywhere where you notice `defined(_MSC_VER)`
(right now I do not have windows environment with mingw to test it out), thanks.

**Comment by hgardneriv** [comment]
Nice work, that fixes the issue!

# make test
Running tests...
Test project C:/code/zip/build
    Start 1: test
1/1 Test #1: test .............................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec

**Comment by kuba--** [comment]
Cool! Could you send a PR or at least diff/patch?

**Comment by hgardneriv** [comment]
See changes attached:


[zip.c.txt](https://github.com/kuba--/zip/files/2251221/zip.c.txt)
