### ISSUE TITLE
sfx

### ISSUE THREAD

**Issue by visiwi** [kuba--/zip#49]
Hello,
Is there a way to unzip sfx archive ?

**Comment by kuba--** [comment]
@visiwi - unfortunatelly no - just regular `zip`:
> Compression: Use the "tdefl" API's.
> Decompression: Use the "tinfl" API's.

**Comment by shinobisoft** [comment]
@kuba-- I realize this has been closed, but I'm compelled to comment... You do realize most sfx's are binary executables with zip archives appended to them. This doesn't apply for all as I have seen the zip archive stored as a resource to the binary, but only on Windows systems. I wrote a wrapper around minizip a few years ago for a scripting language. Part of my wrapper creates sfx's... I wrote the sfx executable... It can be done... Maybe not for all platforms tho. I'm unfamiliar with Linux and Mac  sfx archives.
