### ISSUE TITLE
Implement zip_entry_read

### ISSUE THREAD

**Issue by karliwson** [kuba--/zip#5]
It would be nice to have `zip_entry_read()`. Sometimes we only want to read a single file of an archive, change it and save it back.

I didn't see a simple way to do it.

**Comment by kuba--** [comment]
@karliwson - are you talking about API which let you modify archive _in place_?

**Comment by karliwson** [comment]
@kuba-- No. I'm talking about **reading** a single entry from the archive.

As I understand, we have:

```
/*
  Opens a new entry for writing in a zip archive.
  Returns negative number (< 0) on error, 0 on success.
*/
int zip_entry_open(struct zip_t *zip, const char *entryname);
```

and:

```
/*
  Compresses an input buffer for the current zip entry.
  Returns negative number (< 0) on error, 0 on success.
*/
int zip_entry_write(struct zip_t *zip, const void *buf, size_t bufsize);
```

So, we can directly modify an entry in the archive.

But what about **reading** a single entry from the archive? That's why I wondered something like `zip_entry_read()`.

**Comment by kuba--** [comment]
@karliwson - so far `zip_entry_open` creates a new entry where you can write by `zip_entry_write` or `zip_entry_fwrite`. So, I'm guessing that `zip_entry_read` may extract existing entry into a buffer.

**Comment by karliwson** [comment]
@kuba-- yes, that's it.

**Comment by kuba--** [comment]
@karliwson - I've added `zip_entry_read/fread`. Please take a look if it works for you.
I've also added some examples to the README.

**Comment by karliwson** [comment]
@kuba-- Great. Thank you very much.
