### ISSUE TITLE
fopen_s return is error

### ISSUE THREAD

**Issue by shLuckyCode** [kuba--/zip#50]
https://msdn.microsoft.com/en-us/library/z5hh6ee9.aspx

fopen_s Return Value
Zero if successful; an error code on failure. See errno, _doserrno, _sys_errlist, and _sys_nerr for more information about these error codes.

in **zip_entry_fwrite** function:

#if defined(_MSC_VER) || defined(__MINGW64__)
  if (!fopen_s(&stream, filename, "rb"))
#else
  if (!(stream = fopen(filename, "rb")))
#endif
  {
    // Cannot open filename
    return -1;
  }

change:

#if defined(_MSC_VER) || defined(__MINGW64__)
  if (0 != fopen_s(&stream, filename, "rb"))
#else
  if (!(stream = fopen(filename, "rb")))
#endif
  {
    // Cannot open filename
    return -1;
  }

**Comment by kuba--** [comment]
@shLuckyCode - I've merged a fix into the master. PTAL if it works for you.
