### ISSUE TITLE
Check localtime_s

### ISSUE THREAD

**Issue by drizt** [kuba--/zip#57]
See [this](https://github.com/kuba--/zip/blob/master/src/zip.c#L435). `#define`'s look strange. Furthemore miniz just [check](https://github.com/kuba--/zip/blob/master/src/miniz.h#L4317) only for `_MSC_VER`. I don't sure that `localtime_s` return zero on successful with `__MINGW64__`.

**Comment by drizt** [comment]
miniz [checks](https://github.com/kuba--/zip/blob/master/src/miniz.h#L4317) only for `_MSC_VER`. Probably it will be enough good solution to do the same.

**Comment by drizt** [comment]
P.S. MinGW seems has `_localtime32_s` and `_localtime64_s`. Maybe this can/should be used directly.

**Comment by kuba--** [comment]
@drizt - look at:
https://github.com/kuba--/zip/issues/46
https://github.com/kuba--/zip/pull/47/files

This extra `define` was introduced to fix compilation for _mingw_

**Comment by drizt** [comment]
Hm. I see. Maybe `__MINGW64__` can be replaced with `__MINGW32__`

**Comment by drizt** [comment]
What about [this](https://github.com/kuba--/zip/blob/master/src/zip.c#L440) line? Seems here you tried to use [another](https://en.cppreference.com/w/c/chrono/localtime) `localtime_s` which returns `tm*` get `time_t*` as first argument and `tm*` as second.

**Comment by kuba--** [comment]
Generally we had a distinction between MSVC compiler and other compilers on windows (+Unix), but turned out that for MSYS2 works the same case as for MSVC, so the quickest fix was to add extra _MINGW_ define everywhere where we have MSVC.

**Comment by drizt** [comment]
Maybe `!` should be removed then from 440 line.

**Comment by kuba--** [comment]
if we gonna follow standard `NULL` is on error. Btw check: https://github.com/kuba--/zip/pull/66

**Comment by kuba--** [comment]
I've updated https://github.com/kuba--/zip/pull/66
I think I'll stick to standard otherwise it will be always "crazy mental gymnastics"

**Comment by drizt** [comment]
Checked on Windows with MinGW 4.8.2, 4.9.2 and 5.3.0. Now no any problems. All tests passed. No compilation warnings/errors.

Thanks!
