### ISSUE TITLE
Unzip a file

### ISSUE THREAD

**Issue by BrianBotina** [kuba--/zip#83]
Hello, when I try to uncompress a file in a dir on windows. I have the next problem.
Cannot convert 'int (* (_closure )(const char *,void *))(const char *,void *)' to 'int (*)(const char *,void *)'
I only use the steps in the help.

**Comment by kuba--** [comment]
@BrianBotina - could you send a code snippet which you use? And what compiler do you use?

**Comment by kuba--** [comment]
@BrianBotina - do you still have any issues?
What example did you try?
```c
#include <stdio.h>
#include <zip.h>

int on_extract_entry(const char *filename, void *arg) {
  static int i = 0;
  int n = *(int *)arg;
  printf("Extracted: %s (%d of %d)\n", filename, ++i, n);

  return 0;
}

int main() {
  int arg = 2;
  zip_extract("foo.zip", "/tmp", on_extract_entry, &arg);
  return 0;
}
```
