### ISSUE TITLE
TDM gcc support

### ISSUE THREAD

**Issue by sukhchainn** [kuba--/zip#89]
@kuba-- 
makefiles were generated but what do I need to make object file?
Log is below.
```

Dell@Dell-PC MINGW64 ~/Desktop/zip-master/build
$ make
[ 14%] Building C object CMakeFiles/zip.dir/src/zip.c.obj
In file included from C:\Users\Dell\Desktop\zip-master\src\zip.c:39:0:
C:\Users\Dell\Desktop\zip-master\src\miniz.h: In function 'mz_zip_file_read_func':
C:\Users\Dell\Desktop\zip-master\src\miniz.h:4083:20: error: implicit declaration of function 'ftello64' [-Werror=implicit-function-declaration]
 #define MZ_FTELL64 ftello64
                    ^
C:\Users\Dell\Desktop\zip-master\src\miniz.h:4659:22: note: in expansion of macro 'MZ_FTELL64'
   mz_int64 cur_ofs = MZ_FTELL64(pZip->m_pState->m_pFile);
                      ^
C:\Users\Dell\Desktop\zip-master\src\miniz.h:4084:20: error: implicit declaration of function 'fseeko64' [-Werror=implicit-function-declaration]
 #define MZ_FSEEK64 fseeko64
                    ^
C:\Users\Dell\Desktop\zip-master\src\miniz.h:4662:9: note: in expansion of macro 'MZ_FSEEK64'
        (MZ_FSEEK64(pZip->m_pState->m_pFile, (mz_int64)file_ofs, SEEK_SET))))
         ^
In file included from C:\Users\Dell\Desktop\zip-master\src\zip.c:40:0:
C:\Users\Dell\Desktop\zip-master\src\zip.h: At top level:
C:\Users\Dell\Desktop\zip-master\src\zip.h:24:15: error: conflicting types for 'ssize_t'
 typedef long  ssize_t;  /* byte count or error */
               ^
In file included from I:/TDM-GCC-32/include/sys/stat.h:24:0,
                 from C:\Users\Dell\Desktop\zip-master\src\zip.c:13:
I:/TDM-GCC-32/include/sys/types.h:118:18: note: previous declaration of 'ssize_t' was here
 typedef _ssize_t ssize_t;
                  ^
C:\Users\Dell\Desktop\zip-master\src\zip.c: In function 'zip_entry_fwrite':
C:\Users\Dell\Desktop\zip-master\src\zip.c:596:7: error: implicit declaration of function 'fopen_s' [-Werror=implicit-function-declaration]
   if (fopen_s(&stream, filename, "rb"))
       ^
C:\Users\Dell\Desktop\zip-master\src\zip.c: In function 'zip_extract':
C:\Users\Dell\Desktop\zip-master\src\zip.c:841:3: error: implicit declaration of function 'strcpy_s' [-Werror=implicit-function-declaration]
   strcpy_s(path, MAX_PATH, dir);
   ^
C:\Users\Dell\Desktop\zip-master\src\zip.c:863:5: error: implicit declaration of function 'strncpy_s' [-Werror=implicit-function-declaration]
     strncpy_s(&path[dirlen], MAX_PATH - dirlen, info.m_filename,
     ^
cc1.exe: all warnings being treated as errors
make[2]: *** [CMakeFiles/zip.dir/src/zip.c.obj] Error 1
make[1]: *** [CMakeFiles/zip.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kuba--** [comment]
What environment and compiler do you use?
For a test try to change in `miniz.h` (https://github.com/kuba--/zip/blob/master/src/miniz.h#L4083) `ftello64` to `ftell` and `fseeko64` to `fseek`.

**Comment by sukhchainn** [comment]
I'm using KDM MinGW GCC compiler in windows 7, Git-Bash.
I have MSYS2 installed too.
I have MinGW32 full suit installed.

Do I need Visual Studio too?

On Dec 30, 2018 4:14 AM, "Kuba Podgórski" <notifications@github.com> wrote:

What environment and compiler do you use?
For a test try to change in miniz.h (https://github.com/kuba--/
zip/blob/master/src/miniz.h#L4083) ftello64 to ftell and fseeko64 to fseek.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kuba--/zip/issues/89#issuecomment-450525784>, or mute
the thread

**Comment by kuba--** [comment]
@sukhchainn - I've tried following scenario on my VirtualBox with windows 7:
- Installed mingw: https://sourceforge.net/projects/mingw-w64/
- Installed cmake: https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-win32-x86.msi

In mingw console:
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=true  -G "MinGW Makefiles" ..
```
If cmake fails complaining about `sh` command, just run it the second time and it will generate mingw makefiles.
After that I just run make and everything works fine:
```
mingw32-make.exe
Scanning dependencies of target zip
[ 14%] Building C object CMakeFiles/zip.dir/src/zip.c.obj
[ 28%] Linking C shared library libzip.dll
[ 28%] Built target zip
Scanning dependencies of target test.exe
[ 42%] Building C object test/CMakeFiles/test.exe.dir/test.c.obj
[ 57%] Building C object test/CMakeFiles/test.exe.dir/__/src/zip.c.obj
[ 71%] Linking C executable test.exe.exe
[ 71%] Built target test.exe
Scanning dependencies of target test_miniz.exe
[ 85%] Building C object test/CMakeFiles/test_miniz.exe.dir/test_miniz.c.obj
[100%] Linking C executable test_miniz.exe.exe
[100%] Built target test_miniz.exe

mingw32-make.exe test
Running tests...
Test project C:/Users/IEUser/source/repos/zip/build
    Start 1: test
1/2 Test #1: test .............................   Passed    0.03 sec
    Start 2: test_miniz
2/2 Test #2: test_miniz .......................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   0.05 sec
```

Btw. did you try to replace some functions (if cannot be found - I gave you example above)?

**Comment by kuba--** [comment]
No, you don't need Visual Studio. You need to generate makefiles (or project files) per compiler/platform.

**Comment by sukhchainn** [comment]
@kuba-- 
Still giving some errors.

$ make
[ 14%] Building C object CMakeFiles/zip.dir/src/zip.c.obj
In file included from C:\Users\Dell\Desktop\zip-master\src\zip.c:40:0:
C:\Users\Dell\Desktop\zip-master\src\zip.h:24:15: error: conflicting types for 'ssize_t'
 typedef long  ssize_t;  /* byte count or error */
               ^
In file included from I:/TDM-GCC-32/include/sys/stat.h:24:0,
                 from C:\Users\Dell\Desktop\zip-master\src\zip.c:13:
I:/TDM-GCC-32/include/sys/types.h:118:18: note: previous declaration of 'ssize_t' was here
 typedef _ssize_t ssize_t;
                  ^
C:\Users\Dell\Desktop\zip-master\src\zip.c: In function 'zip_entry_fwrite':
C:\Users\Dell\Desktop\zip-master\src\zip.c:596:7: error: implicit declaration of function 'fopen_s' [-Werror=implicit-function-declaration]
   if (fopen_s(&stream, filename, "rb"))
       ^
C:\Users\Dell\Desktop\zip-master\src\zip.c: In function 'zip_extract':
C:\Users\Dell\Desktop\zip-master\src\zip.c:841:3: error: implicit declaration of function 'strcpy_s' [-Werror=implicit-function-declaration]
   strcpy_s(path, MAX_PATH, dir);
   ^
C:\Users\Dell\Desktop\zip-master\src\zip.c:863:5: error: implicit declaration of function 'strncpy_s' [-Werror=implicit-function-declaration]
     strncpy_s(&path[dirlen], MAX_PATH - dirlen, info.m_filename,
     ^
cc1.exe: all warnings being treated as errors
make[2]: *** [CMakeFiles/zip.dir/src/zip.c.obj] Error 1
make[1]: *** [CMakeFiles/zip.dir/all] Error 2
make: *** [all] Error 2

**Comment by kuba--** [comment]
@sukhchainn - ok I was able to reproduce it. It's a problem with TDM. If you use pure mingw the problem disappears. 
I will take a look what has to be defined/undefined to support TDM flavour of gcc.

**Comment by sukhchainn** [comment]
when I tried with codeblocks's MinGW

```
$ make ..
      7 [main] make (5872) G:\MSYS2\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x1802F4408/0x18031F410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Segmentation fault

```

**Comment by kuba--** [comment]
Why don't you try regular mingw (https://sourceforge.net/projects/mingw-w64/).
*TDM* breaks compatibility. It defines `__MINGW32__` macro but doesn't implement or defines different macros. For instance instead of `_SSIZE_T` it defines `_SSIZE_T_`. Also it doesn't implement `strncpy_s`, `fopen_s`.

**Comment by kuba--** [comment]
@sukhchainn - I've pushed some experimental changes to support TDM-GCC.
Checkout this branch: https://github.com/kuba--/zip/tree/tdm-gcc
I was able to compile and test it on TDM-GCC 32. I hope it won't break anything for pure mingw.

**Comment by sukhchainn** [comment]
when I tried with GNU MinGW
```
$ make
      6 [main] make (6108) G:\MSYS2\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x1802F4408/0x18031F410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Segmentation fault

```

**Comment by sukhchainn** [comment]
Sorry, the problem was in make.
I was using a make from different compiler. That was the problem.

The TDM now generates the object files and executables.
