### ISSUE TITLE
 zip_entry_fwrite(zip, "foo-2.1.txt") fails for big sizes

### ISSUE THREAD

**Issue by ForgottenTales** [kuba--/zip#92]
Writing a zip archive fails when trying to zip big files.

When running in Debug, i get this assertion:
miniz.h:3025: tdefl_compress_lz_codes: Assertion `d->m_huff_code_sizes[1][sym]' failed.

**Comment by kuba--** [comment]
@ForgottenTales - how big is "big"?

**Comment by ForgottenTales** [comment]
Its about 30mb, but the software is running on a very limited (embedded) system. Im not sure how the library does the writing internally, maybe it tries allocate buffers that are to big ?

**Comment by ForgottenTales** [comment]
Im trying to zip the files as follows:



        char* tmp_path = "/tmp/logs.tmp.zip";
        struct zip_t *zip = zip_open(tmp_path, ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
		{
			for (size_t i = 0; i < number_of_files; i++) {
				if (cfileexists(file_paths[i])) {
					DBGLOG("checking file: %s - file exists", file_paths[i]);
					zip_entry_open(zip, file_paths[i]);
					{
						zip_entry_fwrite(zip, file_paths[i]);
					}
					zip_entry_close(zip);
				} else {
					DBGLOG("checking file: %s - file not found", file_paths[i]);
				}
			}
		}
		zip_close(zip);

**Comment by kuba--** [comment]
> ...very limited (embedded) system
Maybe this is the case, because right now I tried and was able to `fwrite` 64MB file.

**Comment by ForgottenTales** [comment]
@kuba-- First of all, Thanks for your quick reply. I will do a bit more testing with various file sizes and other compression levels. Maybe i can figure out what causes this strange behavior. I will let you now about my results here.

**Comment by ForgottenTales** [comment]
@kuba-- Hey there. I solved the problem. There was no problem with the zip library, it was a strange behavior of the OS when handling the temporary storage. So I will close this issue. Thank you !

**Comment by ForgottenTales** [comment]
Im sorry for the confusion, but I have to reopen the issue. The problem is still there.

The problem appears on system architectures that **do not** fit this criteria:

#if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN && MINIZ_HAS_64BIT_REGISTERS

Only in DEBUG mode,  the assertion in miniz.h line 3025 fails:
miniz.h:3025: tdefl_compress_lz_codes: Assertion `d->m_huff_code_sizes[1][sym]' failed.

However, when I simply remove this assertion, then the code runs flawlessly and also produces correct output in every case that I tested.

**Comment by kuba--** [comment]
@ForgottenTales - I was able to compress 64MB files on my arm RPi3 (GCC 6.3) with compression levels 6 and 9. I didn't encounter any issues (`d->m_huff_code_sizes[1][sym]` never was `0`).
On what architecture did you test? Can you add some `println` to debug/check where it comes from.
Maybe this _assert_ is not needed (just nothing will be written for certain symbols and we move on).

**Comment by ForgottenTales** [comment]
Hi @kuba-- Im testing it on a Microblaze architecture (softcore processor), running an 32 bit Petalinux. 

Microblaze: https://www.xilinx.com/products/design-tools/microblaze.html

I will do some debugging later and give you more information about the problem.

**Comment by kuba--** [comment]
Ok, cool. Thanks!
Btw. I'm curious - where are you going to use it?

**Comment by ForgottenTales** [comment]
Hi @kuba-- sry for the late reply. I tested it again. And I am now quite sure that the mentioned assertion can just be removed. And then everything works as intended. I didnt track it down whats the reason behind this, somehow d->m_huff_code_sizes[1][sym] is 0, but its running for a long time now already (without the assertion). Very stable.

The Software is used in an hardware similar to a switch, the zipping is used to fetch large log files from the system.

**Comment by kuba--** [comment]
OK, would you mind opening PR?

**Comment by ForgottenTales** [comment]
yeah sure!

**Comment by ForgottenTales** [comment]
@kuba-- i created a local branch and applied the fix. but I get denied to push the branch upstream. How to do it? Sry, I am not familiar with github.

**Comment by kuba--** [comment]
you have to fork the repo and send pr across forks
