### ISSUE TITLE
hava miniz.c file?

### ISSUE THREAD

**Issue by ClearSeve** [kuba--/zip#93]

**Comment by kuba--** [comment]
@ClearSeve - for include convenience I combined all in one `.h`. But if you are interested in miniz implementation take a look here: https://github.com/richgel999/miniz

**Comment by ClearSeve** [comment]
> @ClearSeve - 为方便起见，我将所有功能合二为一`.h`。但如果你对迷你实现感兴趣，请看一下：[https](https://github.com/richgel999/miniz)：[//github.com/richgel999/miniz](https://github.com/richgel999/miniz)

Thank man
